// Code generated by Kitex v0.16.2. DO NOT EDIT.

package feedbackservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "github.com/west2-online/fzuhelper-server/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateFeedback": kitex.NewMethodInfo(
		createFeedbackHandler,
		newFeedbackServiceCreateFeedbackArgs,
		newFeedbackServiceCreateFeedbackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFeedbackByID": kitex.NewMethodInfo(
		getFeedbackByIDHandler,
		newFeedbackServiceGetFeedbackByIDArgs,
		newFeedbackServiceGetFeedbackByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFeedback": kitex.NewMethodInfo(
		listFeedbackHandler,
		newFeedbackServiceListFeedbackArgs,
		newFeedbackServiceListFeedbackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	feedbackServiceServiceInfo                = NewServiceInfo()
	feedbackServiceServiceInfoForClient       = NewServiceInfoForClient()
	feedbackServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return feedbackServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return feedbackServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return feedbackServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FeedbackService"
	handlerType := (*api.FeedbackService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createFeedbackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.FeedbackServiceCreateFeedbackArgs)
	realResult := result.(*api.FeedbackServiceCreateFeedbackResult)
	success, err := handler.(api.FeedbackService).CreateFeedback(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedbackServiceCreateFeedbackArgs() interface{} {
	return api.NewFeedbackServiceCreateFeedbackArgs()
}

func newFeedbackServiceCreateFeedbackResult() interface{} {
	return api.NewFeedbackServiceCreateFeedbackResult()
}

func getFeedbackByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.FeedbackServiceGetFeedbackByIDArgs)
	realResult := result.(*api.FeedbackServiceGetFeedbackByIDResult)
	success, err := handler.(api.FeedbackService).GetFeedbackByID(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedbackServiceGetFeedbackByIDArgs() interface{} {
	return api.NewFeedbackServiceGetFeedbackByIDArgs()
}

func newFeedbackServiceGetFeedbackByIDResult() interface{} {
	return api.NewFeedbackServiceGetFeedbackByIDResult()
}

func listFeedbackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.FeedbackServiceListFeedbackArgs)
	realResult := result.(*api.FeedbackServiceListFeedbackResult)
	success, err := handler.(api.FeedbackService).ListFeedback(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedbackServiceListFeedbackArgs() interface{} {
	return api.NewFeedbackServiceListFeedbackArgs()
}

func newFeedbackServiceListFeedbackResult() interface{} {
	return api.NewFeedbackServiceListFeedbackResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateFeedback(ctx context.Context, request *api.CreateFeedbackRequest) (r *api.CreateFeedbackResponse, err error) {
	var _args api.FeedbackServiceCreateFeedbackArgs
	_args.Request = request
	var _result api.FeedbackServiceCreateFeedbackResult
	if err = p.c.Call(ctx, "CreateFeedback", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFeedbackByID(ctx context.Context, request *api.GetFeedbackByIDRequest) (r *api.FeedbackDetailResponse, err error) {
	var _args api.FeedbackServiceGetFeedbackByIDArgs
	_args.Request = request
	var _result api.FeedbackServiceGetFeedbackByIDResult
	if err = p.c.Call(ctx, "GetFeedbackByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFeedback(ctx context.Context, request *api.GetListFeedbackRequest) (r *api.GetListFeedbackResponse, err error) {
	var _args api.FeedbackServiceListFeedbackArgs
	_args.Request = request
	var _result api.FeedbackServiceListFeedbackResult
	if err = p.c.Call(ctx, "ListFeedback", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
