/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kitex v0.15.4. DO NOT EDIT.

package oa

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/west2-online/fzuhelper-server/kitex_gen/model"
)

var (
	_ = model.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type OAServiceCreateFeedbackArgs struct {
	Request *CreateFeedbackRequest `thrift:"request,1" frugal:"1,default,CreateFeedbackRequest" json:"request"`
}

func NewOAServiceCreateFeedbackArgs() *OAServiceCreateFeedbackArgs {
	return &OAServiceCreateFeedbackArgs{}
}

func (p *OAServiceCreateFeedbackArgs) InitDefault() {
}

var OAServiceCreateFeedbackArgs_Request_DEFAULT *CreateFeedbackRequest

func (p *OAServiceCreateFeedbackArgs) GetRequest() (v *CreateFeedbackRequest) {
	if !p.IsSetRequest() {
		return OAServiceCreateFeedbackArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OAServiceCreateFeedbackArgs) SetRequest(val *CreateFeedbackRequest) {
	p.Request = val
}

func (p *OAServiceCreateFeedbackArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OAServiceCreateFeedbackArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceCreateFeedbackArgs(%+v)", *p)
}

func (p *OAServiceCreateFeedbackArgs) GetFirstArgument() interface{} {
	return p.Request
}

type OAServiceCreateFeedbackResult struct {
	Success *CreateFeedbackResponse `thrift:"success,0,optional" frugal:"0,optional,CreateFeedbackResponse" json:"success,omitempty"`
}

func NewOAServiceCreateFeedbackResult() *OAServiceCreateFeedbackResult {
	return &OAServiceCreateFeedbackResult{}
}

func (p *OAServiceCreateFeedbackResult) InitDefault() {
}

var OAServiceCreateFeedbackResult_Success_DEFAULT *CreateFeedbackResponse

func (p *OAServiceCreateFeedbackResult) GetSuccess() (v *CreateFeedbackResponse) {
	if !p.IsSetSuccess() {
		return OAServiceCreateFeedbackResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OAServiceCreateFeedbackResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateFeedbackResponse)
}

func (p *OAServiceCreateFeedbackResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OAServiceCreateFeedbackResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceCreateFeedbackResult(%+v)", *p)
}

func (p *OAServiceCreateFeedbackResult) GetResult() interface{} {
	return p.Success
}

type OAServiceGetFeedbackByIdArgs struct {
	Request *GetFeedbackByIDRequest `thrift:"request,1" frugal:"1,default,GetFeedbackByIDRequest" json:"request"`
}

func NewOAServiceGetFeedbackByIdArgs() *OAServiceGetFeedbackByIdArgs {
	return &OAServiceGetFeedbackByIdArgs{}
}

func (p *OAServiceGetFeedbackByIdArgs) InitDefault() {
}

var OAServiceGetFeedbackByIdArgs_Request_DEFAULT *GetFeedbackByIDRequest

func (p *OAServiceGetFeedbackByIdArgs) GetRequest() (v *GetFeedbackByIDRequest) {
	if !p.IsSetRequest() {
		return OAServiceGetFeedbackByIdArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OAServiceGetFeedbackByIdArgs) SetRequest(val *GetFeedbackByIDRequest) {
	p.Request = val
}

func (p *OAServiceGetFeedbackByIdArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OAServiceGetFeedbackByIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceGetFeedbackByIdArgs(%+v)", *p)
}

func (p *OAServiceGetFeedbackByIdArgs) GetFirstArgument() interface{} {
	return p.Request
}

type OAServiceGetFeedbackByIdResult struct {
	Success *FeedbackDetailResponse `thrift:"success,0,optional" frugal:"0,optional,FeedbackDetailResponse" json:"success,omitempty"`
}

func NewOAServiceGetFeedbackByIdResult() *OAServiceGetFeedbackByIdResult {
	return &OAServiceGetFeedbackByIdResult{}
}

func (p *OAServiceGetFeedbackByIdResult) InitDefault() {
}

var OAServiceGetFeedbackByIdResult_Success_DEFAULT *FeedbackDetailResponse

func (p *OAServiceGetFeedbackByIdResult) GetSuccess() (v *FeedbackDetailResponse) {
	if !p.IsSetSuccess() {
		return OAServiceGetFeedbackByIdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OAServiceGetFeedbackByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*FeedbackDetailResponse)
}

func (p *OAServiceGetFeedbackByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OAServiceGetFeedbackByIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceGetFeedbackByIdResult(%+v)", *p)
}

func (p *OAServiceGetFeedbackByIdResult) GetResult() interface{} {
	return p.Success
}

type OAServiceGetFeedbackListArgs struct {
	Request *GetListFeedbackRequest `thrift:"request,1" frugal:"1,default,GetListFeedbackRequest" json:"request"`
}

func NewOAServiceGetFeedbackListArgs() *OAServiceGetFeedbackListArgs {
	return &OAServiceGetFeedbackListArgs{}
}

func (p *OAServiceGetFeedbackListArgs) InitDefault() {
}

var OAServiceGetFeedbackListArgs_Request_DEFAULT *GetListFeedbackRequest

func (p *OAServiceGetFeedbackListArgs) GetRequest() (v *GetListFeedbackRequest) {
	if !p.IsSetRequest() {
		return OAServiceGetFeedbackListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *OAServiceGetFeedbackListArgs) SetRequest(val *GetListFeedbackRequest) {
	p.Request = val
}

func (p *OAServiceGetFeedbackListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OAServiceGetFeedbackListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceGetFeedbackListArgs(%+v)", *p)
}

func (p *OAServiceGetFeedbackListArgs) GetFirstArgument() interface{} {
	return p.Request
}

type OAServiceGetFeedbackListResult struct {
	Success *GetListFeedbackResponse `thrift:"success,0,optional" frugal:"0,optional,GetListFeedbackResponse" json:"success,omitempty"`
}

func NewOAServiceGetFeedbackListResult() *OAServiceGetFeedbackListResult {
	return &OAServiceGetFeedbackListResult{}
}

func (p *OAServiceGetFeedbackListResult) InitDefault() {
}

var OAServiceGetFeedbackListResult_Success_DEFAULT *GetListFeedbackResponse

func (p *OAServiceGetFeedbackListResult) GetSuccess() (v *GetListFeedbackResponse) {
	if !p.IsSetSuccess() {
		return OAServiceGetFeedbackListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OAServiceGetFeedbackListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetListFeedbackResponse)
}

func (p *OAServiceGetFeedbackListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OAServiceGetFeedbackListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OAServiceGetFeedbackListResult(%+v)", *p)
}

func (p *OAServiceGetFeedbackListResult) GetResult() interface{} {
	return p.Success
}
