codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 60..100

ignore:
  - "**/cmd/**"
  - "**/config/**"
  - "**/kitex_gen/**"
  - "**/idl/**"
  - "**/hack/**"
  - "**/docs/**"
  - "**/api/router/**"
  - "**/middleware/**"
  - "**/model/**"
  - "**/pack/**"


comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes