
services:

  fzu-helper-redis:
    container_name: fzu-helper-redis
    image: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - fzu-helper


  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"
    networks:
      - fzu-helper
  api:
    image: api_image
    networks:
      - fzu-helper
    container_name: api
    restart: always
    ports:
      - "20001:20001"
    command: sh -c 'sleep 3600 & ./api'

  classroom:
    image: classroom_image
    networks:
      - fzu-helper
    container_name: classroom
    restart: always
    ports:
      - "20002:20002"
    command: sh -c './classroom'

  user:
    image: user_image
    networks:
      - fzu-helper
    container_name: user
    restart: always
    ports:
      - "20003:20003"
    command: sh -c './user'


networks:
  fzu-helper:
    driver: bridge
