
services:


  redis:
    image: redis:latest
    container_name: fzu-helper-redis
    environment:
      - REDIS_PASSWORD="fzu-helper"
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - fzu-helper
    command: [ "redis-server", "--requirepass", "fzu-helper" ]


  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"
    networks:
      - fzu-helper
  api:
    image: api_image
    networks:
      - fzu-helper
    container_name: api
    restart: always
    ports:
      - "10001:10001"
    command: sh -c 'sleep 3600 & ./api'

  classroom:
    image: classroom_image
    networks:
      - fzu-helper
    container_name: classroom
    restart: always
    ports:
      - "10002:10002"
    command: sh -c './classroom'


networks:
  fzu-helper:
    driver: bridge
