services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    container_name: uptrace-clickhouse
    restart: on-failure
    environment:
      CLICKHOUSE_USER: uptrace
      CLICKHOUSE_PASSWORD: uptrace
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ../data/ch:/var/lib/clickhouse
    env_file:
      - ../env/uptrace.env
    ports:
      - '8123:8123'
      - '9000:9000'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
    networks:
      - fzuhelper

  postgres:
    image: postgres:17-alpine
    container_name: uptrace-postgres
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uptrace -d uptrace']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ../data/pg:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    networks:
      - fzuhelper

  redis:
    image: redis:6.2.2-alpine
    container_name: uptrace-redis
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 1s
      retries: 30
    networks:
      - fzuhelper

  uptrace:
    image: 'uptrace/uptrace:2.1.0-beta.5'
    container_name: fzuhelper-uptrace
    restart: on-failure
    volumes:
      - ../../config/uptrace/uptrace.yml:/etc/uptrace/config.yml
    ports:
      - '14317:4317'
      - '14318:80'
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fzuhelper

networks:
  fzuhelper:
    external: true # 使用主compose里的 fzuhelper 网络

