// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "github.com/west2-online/fzuhelper-server/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetLoginData": kitex.NewMethodInfo(
		getLoginDataHandler,
		newUserServiceGetLoginDataArgs,
		newUserServiceGetLoginDataResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGetLoginDataForYJSY": kitex.NewMethodInfo(
		getGetLoginDataForYJSYHandler,
		newUserServiceGetGetLoginDataForYJSYArgs,
		newUserServiceGetGetLoginDataForYJSYResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetToken": kitex.NewMethodInfo(
		getTokenHandler,
		newUserServiceGetTokenArgs,
		newUserServiceGetTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newUserServiceRefreshTokenArgs,
		newUserServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TestAuth": kitex.NewMethodInfo(
		testAuthHandler,
		newUserServiceTestAuthArgs,
		newUserServiceTestAuthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetInvitationCode": kitex.NewMethodInfo(
		getInvitationCodeHandler,
		newUserServiceGetInvitationCodeArgs,
		newUserServiceGetInvitationCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindInvitation": kitex.NewMethodInfo(
		bindInvitationHandler,
		newUserServiceBindInvitationArgs,
		newUserServiceBindInvitationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendList": kitex.NewMethodInfo(
		getFriendListHandler,
		newUserServiceGetFriendListArgs,
		newUserServiceGetFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFriend": kitex.NewMethodInfo(
		deleteFriendHandler,
		newUserServiceDeleteFriendArgs,
		newUserServiceDeleteFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelInvite": kitex.NewMethodInfo(
		cancelInviteHandler,
		newUserServiceCancelInviteArgs,
		newUserServiceCancelInviteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendMaxNum": kitex.NewMethodInfo(
		getFriendMaxNumHandler,
		newUserServiceGetFriendMaxNumArgs,
		newUserServiceGetFriendMaxNumResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReorderFriendList": kitex.NewMethodInfo(
		reorderFriendListHandler,
		newUserServiceReorderFriendListArgs,
		newUserServiceReorderFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*api.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getLoginDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetLoginDataArgs)
	realResult := result.(*api.UserServiceGetLoginDataResult)
	success, err := handler.(api.UserService).GetLoginData(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetLoginDataArgs() interface{} {
	return api.NewUserServiceGetLoginDataArgs()
}

func newUserServiceGetLoginDataResult() interface{} {
	return api.NewUserServiceGetLoginDataResult()
}

func getGetLoginDataForYJSYHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetGetLoginDataForYJSYArgs)
	realResult := result.(*api.UserServiceGetGetLoginDataForYJSYResult)
	success, err := handler.(api.UserService).GetGetLoginDataForYJSY(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetGetLoginDataForYJSYArgs() interface{} {
	return api.NewUserServiceGetGetLoginDataForYJSYArgs()
}

func newUserServiceGetGetLoginDataForYJSYResult() interface{} {
	return api.NewUserServiceGetGetLoginDataForYJSYResult()
}

func getTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetTokenArgs)
	realResult := result.(*api.UserServiceGetTokenResult)
	success, err := handler.(api.UserService).GetToken(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetTokenArgs() interface{} {
	return api.NewUserServiceGetTokenArgs()
}

func newUserServiceGetTokenResult() interface{} {
	return api.NewUserServiceGetTokenResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceRefreshTokenArgs)
	realResult := result.(*api.UserServiceRefreshTokenResult)
	success, err := handler.(api.UserService).RefreshToken(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRefreshTokenArgs() interface{} {
	return api.NewUserServiceRefreshTokenArgs()
}

func newUserServiceRefreshTokenResult() interface{} {
	return api.NewUserServiceRefreshTokenResult()
}

func testAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceTestAuthArgs)
	realResult := result.(*api.UserServiceTestAuthResult)
	success, err := handler.(api.UserService).TestAuth(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceTestAuthArgs() interface{} {
	return api.NewUserServiceTestAuthArgs()
}

func newUserServiceTestAuthResult() interface{} {
	return api.NewUserServiceTestAuthResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetUserInfoArgs)
	realResult := result.(*api.UserServiceGetUserInfoResult)
	success, err := handler.(api.UserService).GetUserInfo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return api.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return api.NewUserServiceGetUserInfoResult()
}

func getInvitationCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetInvitationCodeArgs)
	realResult := result.(*api.UserServiceGetInvitationCodeResult)
	success, err := handler.(api.UserService).GetInvitationCode(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetInvitationCodeArgs() interface{} {
	return api.NewUserServiceGetInvitationCodeArgs()
}

func newUserServiceGetInvitationCodeResult() interface{} {
	return api.NewUserServiceGetInvitationCodeResult()
}

func bindInvitationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceBindInvitationArgs)
	realResult := result.(*api.UserServiceBindInvitationResult)
	success, err := handler.(api.UserService).BindInvitation(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBindInvitationArgs() interface{} {
	return api.NewUserServiceBindInvitationArgs()
}

func newUserServiceBindInvitationResult() interface{} {
	return api.NewUserServiceBindInvitationResult()
}

func getFriendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetFriendListArgs)
	realResult := result.(*api.UserServiceGetFriendListResult)
	success, err := handler.(api.UserService).GetFriendList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetFriendListArgs() interface{} {
	return api.NewUserServiceGetFriendListArgs()
}

func newUserServiceGetFriendListResult() interface{} {
	return api.NewUserServiceGetFriendListResult()
}

func deleteFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceDeleteFriendArgs)
	realResult := result.(*api.UserServiceDeleteFriendResult)
	success, err := handler.(api.UserService).DeleteFriend(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteFriendArgs() interface{} {
	return api.NewUserServiceDeleteFriendArgs()
}

func newUserServiceDeleteFriendResult() interface{} {
	return api.NewUserServiceDeleteFriendResult()
}

func cancelInviteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceCancelInviteArgs)
	realResult := result.(*api.UserServiceCancelInviteResult)
	success, err := handler.(api.UserService).CancelInvite(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCancelInviteArgs() interface{} {
	return api.NewUserServiceCancelInviteArgs()
}

func newUserServiceCancelInviteResult() interface{} {
	return api.NewUserServiceCancelInviteResult()
}

func getFriendMaxNumHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetFriendMaxNumArgs)
	realResult := result.(*api.UserServiceGetFriendMaxNumResult)
	success, err := handler.(api.UserService).GetFriendMaxNum(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetFriendMaxNumArgs() interface{} {
	return api.NewUserServiceGetFriendMaxNumArgs()
}

func newUserServiceGetFriendMaxNumResult() interface{} {
	return api.NewUserServiceGetFriendMaxNumResult()
}

func reorderFriendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceReorderFriendListArgs)
	realResult := result.(*api.UserServiceReorderFriendListResult)
	success, err := handler.(api.UserService).ReorderFriendList(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceReorderFriendListArgs() interface{} {
	return api.NewUserServiceReorderFriendListArgs()
}

func newUserServiceReorderFriendListResult() interface{} {
	return api.NewUserServiceReorderFriendListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetLoginData(ctx context.Context, request *api.GetLoginDataRequest) (r *api.GetLoginDataResponse, err error) {
	var _args api.UserServiceGetLoginDataArgs
	_args.Request = request
	var _result api.UserServiceGetLoginDataResult
	if err = p.c.Call(ctx, "GetLoginData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGetLoginDataForYJSY(ctx context.Context, request *api.GetLoginDataForYJSYRequest) (r *api.GetLoginDataForYJSYResponse, err error) {
	var _args api.UserServiceGetGetLoginDataForYJSYArgs
	_args.Request = request
	var _result api.UserServiceGetGetLoginDataForYJSYResult
	if err = p.c.Call(ctx, "GetGetLoginDataForYJSY", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetToken(ctx context.Context, request *api.GetAccessTokenRequest) (r *api.GetAccessTokenResponse, err error) {
	var _args api.UserServiceGetTokenArgs
	_args.Request = request
	var _result api.UserServiceGetTokenResult
	if err = p.c.Call(ctx, "GetToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, request *api.RefreshTokenRequest) (r *api.RefreshTokenResponse, err error) {
	var _args api.UserServiceRefreshTokenArgs
	_args.Request = request
	var _result api.UserServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TestAuth(ctx context.Context, request *api.TestAuthRequest) (r *api.TestAuthResponse, err error) {
	var _args api.UserServiceTestAuthArgs
	_args.Request = request
	var _result api.UserServiceTestAuthResult
	if err = p.c.Call(ctx, "TestAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, request *api.GetUserInfoRequest) (r *api.GetUserInfoResponse, err error) {
	var _args api.UserServiceGetUserInfoArgs
	_args.Request = request
	var _result api.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInvitationCode(ctx context.Context, request *api.GetInvitationCodeRequest) (r *api.GetInvitationCodeResponse, err error) {
	var _args api.UserServiceGetInvitationCodeArgs
	_args.Request = request
	var _result api.UserServiceGetInvitationCodeResult
	if err = p.c.Call(ctx, "GetInvitationCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindInvitation(ctx context.Context, request *api.BindInvitationRequest) (r *api.BindInvitationResponse, err error) {
	var _args api.UserServiceBindInvitationArgs
	_args.Request = request
	var _result api.UserServiceBindInvitationResult
	if err = p.c.Call(ctx, "BindInvitation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendList(ctx context.Context, request *api.GetFriendListRequest) (r *api.GetFriendListResponse, err error) {
	var _args api.UserServiceGetFriendListArgs
	_args.Request = request
	var _result api.UserServiceGetFriendListResult
	if err = p.c.Call(ctx, "GetFriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFriend(ctx context.Context, request *api.DeleteFriendRequest) (r *api.DeleteFriendResponse, err error) {
	var _args api.UserServiceDeleteFriendArgs
	_args.Request = request
	var _result api.UserServiceDeleteFriendResult
	if err = p.c.Call(ctx, "DeleteFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelInvite(ctx context.Context, request *api.CancelInviteRequest) (r *api.CancelInviteResponse, err error) {
	var _args api.UserServiceCancelInviteArgs
	_args.Request = request
	var _result api.UserServiceCancelInviteResult
	if err = p.c.Call(ctx, "CancelInvite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendMaxNum(ctx context.Context, request *api.GetFriendMaxNumRequest) (r *api.GetFriendMaxNumResponse, err error) {
	var _args api.UserServiceGetFriendMaxNumArgs
	_args.Request = request
	var _result api.UserServiceGetFriendMaxNumResult
	if err = p.c.Call(ctx, "GetFriendMaxNum", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReorderFriendList(ctx context.Context, request *api.ReorderFriendListRequest) (r *api.ReorderFriendListResponse, err error) {
	var _args api.UserServiceReorderFriendListArgs
	_args.Request = request
	var _result api.UserServiceReorderFriendListResult
	if err = p.c.Call(ctx, "ReorderFriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
