/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package model

import (
	"fmt"
)

type CreditResponse = []*CreditCategory

type BaseResp struct {
	Code int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int64) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

type LoginData struct {
	Id      string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Cookies string `thrift:"cookies,2,required" frugal:"2,required,string" json:"cookies"`
}

func NewLoginData() *LoginData {
	return &LoginData{}
}

func (p *LoginData) InitDefault() {
}

func (p *LoginData) GetId() (v string) {
	return p.Id
}

func (p *LoginData) GetCookies() (v string) {
	return p.Cookies
}
func (p *LoginData) SetId(val string) {
	p.Id = val
}
func (p *LoginData) SetCookies(val string) {
	p.Cookies = val
}

func (p *LoginData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginData(%+v)", *p)
}

type UserInfo struct {
	StuId    string `thrift:"stu_id,1,required" frugal:"1,required,string" json:"stu_id"`
	Name     string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	Birthday string `thrift:"birthday,3,required" frugal:"3,required,string" json:"birthday"`
	Sex      string `thrift:"sex,4,required" frugal:"4,required,string" json:"sex"`
	College  string `thrift:"college,5,required" frugal:"5,required,string" json:"college"`
	Grade    string `thrift:"grade,6,required" frugal:"6,required,string" json:"grade"`
	Major    string `thrift:"major,7,required" frugal:"7,required,string" json:"major"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetStuId() (v string) {
	return p.StuId
}

func (p *UserInfo) GetName() (v string) {
	return p.Name
}

func (p *UserInfo) GetBirthday() (v string) {
	return p.Birthday
}

func (p *UserInfo) GetSex() (v string) {
	return p.Sex
}

func (p *UserInfo) GetCollege() (v string) {
	return p.College
}

func (p *UserInfo) GetGrade() (v string) {
	return p.Grade
}

func (p *UserInfo) GetMajor() (v string) {
	return p.Major
}
func (p *UserInfo) SetStuId(val string) {
	p.StuId = val
}
func (p *UserInfo) SetName(val string) {
	p.Name = val
}
func (p *UserInfo) SetBirthday(val string) {
	p.Birthday = val
}
func (p *UserInfo) SetSex(val string) {
	p.Sex = val
}
func (p *UserInfo) SetCollege(val string) {
	p.College = val
}
func (p *UserInfo) SetGrade(val string) {
	p.Grade = val
}
func (p *UserInfo) SetMajor(val string) {
	p.Major = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

type UserFriendInfo struct {
	StuId     string `thrift:"stu_id,1,required" frugal:"1,required,string" json:"stu_id"`
	Name      string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	College   string `thrift:"college,3,required" frugal:"3,required,string" json:"college"`
	Grade     string `thrift:"grade,4,required" frugal:"4,required,string" json:"grade"`
	Major     string `thrift:"major,5,required" frugal:"5,required,string" json:"major"`
	CreatedAt int64  `thrift:"created_at,6,required" frugal:"6,required,i64" json:"created_at"`
	OrderSeq  int64  `thrift:"order_seq,7,required" frugal:"7,required,i64" json:"order_seq"`
}

func NewUserFriendInfo() *UserFriendInfo {
	return &UserFriendInfo{}
}

func (p *UserFriendInfo) InitDefault() {
}

func (p *UserFriendInfo) GetStuId() (v string) {
	return p.StuId
}

func (p *UserFriendInfo) GetName() (v string) {
	return p.Name
}

func (p *UserFriendInfo) GetCollege() (v string) {
	return p.College
}

func (p *UserFriendInfo) GetGrade() (v string) {
	return p.Grade
}

func (p *UserFriendInfo) GetMajor() (v string) {
	return p.Major
}

func (p *UserFriendInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *UserFriendInfo) GetOrderSeq() (v int64) {
	return p.OrderSeq
}
func (p *UserFriendInfo) SetStuId(val string) {
	p.StuId = val
}
func (p *UserFriendInfo) SetName(val string) {
	p.Name = val
}
func (p *UserFriendInfo) SetCollege(val string) {
	p.College = val
}
func (p *UserFriendInfo) SetGrade(val string) {
	p.Grade = val
}
func (p *UserFriendInfo) SetMajor(val string) {
	p.Major = val
}
func (p *UserFriendInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *UserFriendInfo) SetOrderSeq(val int64) {
	p.OrderSeq = val
}

func (p *UserFriendInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserFriendInfo(%+v)", *p)
}

type FriendMaxNumInfo struct {
	MaxNum int64 `thrift:"max_num,1,required" frugal:"1,required,i64" json:"max_num"`
}

func NewFriendMaxNumInfo() *FriendMaxNumInfo {
	return &FriendMaxNumInfo{}
}

func (p *FriendMaxNumInfo) InitDefault() {
}

func (p *FriendMaxNumInfo) GetMaxNum() (v int64) {
	return p.MaxNum
}
func (p *FriendMaxNumInfo) SetMaxNum(val int64) {
	p.MaxNum = val
}

func (p *FriendMaxNumInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendMaxNumInfo(%+v)", *p)
}

type Classroom struct {
	Build    string `thrift:"build,1,required" frugal:"1,required,string" json:"build"`
	Location string `thrift:"location,2,required" frugal:"2,required,string" json:"location"`
	Capacity string `thrift:"capacity,3,required" frugal:"3,required,string" json:"capacity"`
	Type     string `thrift:"type,4,required" frugal:"4,required,string" json:"type"`
}

func NewClassroom() *Classroom {
	return &Classroom{}
}

func (p *Classroom) InitDefault() {
}

func (p *Classroom) GetBuild() (v string) {
	return p.Build
}

func (p *Classroom) GetLocation() (v string) {
	return p.Location
}

func (p *Classroom) GetCapacity() (v string) {
	return p.Capacity
}

func (p *Classroom) GetType() (v string) {
	return p.Type
}
func (p *Classroom) SetBuild(val string) {
	p.Build = val
}
func (p *Classroom) SetLocation(val string) {
	p.Location = val
}
func (p *Classroom) SetCapacity(val string) {
	p.Capacity = val
}
func (p *Classroom) SetType(val string) {
	p.Type = val
}

func (p *Classroom) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Classroom(%+v)", *p)
}

type ExamRoomInfo struct {
	Name     string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Credit   string `thrift:"credit,2,required" frugal:"2,required,string" json:"credit"`
	Teacher  string `thrift:"teacher,3,required" frugal:"3,required,string" json:"teacher"`
	Location string `thrift:"location,4,required" frugal:"4,required,string" json:"location"`
	Time     string `thrift:"time,5,required" frugal:"5,required,string" json:"time"`
	Date     string `thrift:"date,6,required" frugal:"6,required,string" json:"date"`
}

func NewExamRoomInfo() *ExamRoomInfo {
	return &ExamRoomInfo{}
}

func (p *ExamRoomInfo) InitDefault() {
}

func (p *ExamRoomInfo) GetName() (v string) {
	return p.Name
}

func (p *ExamRoomInfo) GetCredit() (v string) {
	return p.Credit
}

func (p *ExamRoomInfo) GetTeacher() (v string) {
	return p.Teacher
}

func (p *ExamRoomInfo) GetLocation() (v string) {
	return p.Location
}

func (p *ExamRoomInfo) GetTime() (v string) {
	return p.Time
}

func (p *ExamRoomInfo) GetDate() (v string) {
	return p.Date
}
func (p *ExamRoomInfo) SetName(val string) {
	p.Name = val
}
func (p *ExamRoomInfo) SetCredit(val string) {
	p.Credit = val
}
func (p *ExamRoomInfo) SetTeacher(val string) {
	p.Teacher = val
}
func (p *ExamRoomInfo) SetLocation(val string) {
	p.Location = val
}
func (p *ExamRoomInfo) SetTime(val string) {
	p.Time = val
}
func (p *ExamRoomInfo) SetDate(val string) {
	p.Date = val
}

func (p *ExamRoomInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExamRoomInfo(%+v)", *p)
}

type CourseScheduleRule struct {
	Location   string `thrift:"location,1,required" frugal:"1,required,string" json:"location"`
	StartClass int64  `thrift:"startClass,2,required" frugal:"2,required,i64" json:"startClass"`
	EndClass   int64  `thrift:"endClass,3,required" frugal:"3,required,i64" json:"endClass"`
	StartWeek  int64  `thrift:"startWeek,4,required" frugal:"4,required,i64" json:"startWeek"`
	EndWeek    int64  `thrift:"endWeek,5,required" frugal:"5,required,i64" json:"endWeek"`
	Weekday    int64  `thrift:"weekday,6,required" frugal:"6,required,i64" json:"weekday"`
	Single     bool   `thrift:"single,7,required" frugal:"7,required,bool" json:"single"`
	Double     bool   `thrift:"double,8,required" frugal:"8,required,bool" json:"double"`
	Adjust     bool   `thrift:"adjust,9,required" frugal:"9,required,bool" json:"adjust"`
}

func NewCourseScheduleRule() *CourseScheduleRule {
	return &CourseScheduleRule{}
}

func (p *CourseScheduleRule) InitDefault() {
}

func (p *CourseScheduleRule) GetLocation() (v string) {
	return p.Location
}

func (p *CourseScheduleRule) GetStartClass() (v int64) {
	return p.StartClass
}

func (p *CourseScheduleRule) GetEndClass() (v int64) {
	return p.EndClass
}

func (p *CourseScheduleRule) GetStartWeek() (v int64) {
	return p.StartWeek
}

func (p *CourseScheduleRule) GetEndWeek() (v int64) {
	return p.EndWeek
}

func (p *CourseScheduleRule) GetWeekday() (v int64) {
	return p.Weekday
}

func (p *CourseScheduleRule) GetSingle() (v bool) {
	return p.Single
}

func (p *CourseScheduleRule) GetDouble() (v bool) {
	return p.Double
}

func (p *CourseScheduleRule) GetAdjust() (v bool) {
	return p.Adjust
}
func (p *CourseScheduleRule) SetLocation(val string) {
	p.Location = val
}
func (p *CourseScheduleRule) SetStartClass(val int64) {
	p.StartClass = val
}
func (p *CourseScheduleRule) SetEndClass(val int64) {
	p.EndClass = val
}
func (p *CourseScheduleRule) SetStartWeek(val int64) {
	p.StartWeek = val
}
func (p *CourseScheduleRule) SetEndWeek(val int64) {
	p.EndWeek = val
}
func (p *CourseScheduleRule) SetWeekday(val int64) {
	p.Weekday = val
}
func (p *CourseScheduleRule) SetSingle(val bool) {
	p.Single = val
}
func (p *CourseScheduleRule) SetDouble(val bool) {
	p.Double = val
}
func (p *CourseScheduleRule) SetAdjust(val bool) {
	p.Adjust = val
}

func (p *CourseScheduleRule) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseScheduleRule(%+v)", *p)
}

type CourseAdjustRule struct {
	OldWeek        int64  `thrift:"oldWeek,1,required" frugal:"1,required,i64" json:"oldWeek"`
	OldDay         int64  `thrift:"oldDay,2,required" frugal:"2,required,i64" json:"oldDay"`
	OldStartClass  int64  `thrift:"oldStartClass,3,required" frugal:"3,required,i64" json:"oldStartClass"`
	OldEndClass    int64  `thrift:"oldEndClass,4,required" frugal:"4,required,i64" json:"oldEndClass"`
	Canceled       bool   `thrift:"canceled,5,required" frugal:"5,required,bool" json:"canceled"`
	NewWeek_       int64  `thrift:"newWeek,6,required" frugal:"6,required,i64" json:"newWeek"`
	NewDay_        int64  `thrift:"newDay,7,required" frugal:"7,required,i64" json:"newDay"`
	NewStartClass_ int64  `thrift:"newStartClass,8,required" frugal:"8,required,i64" json:"newStartClass"`
	NewEndClass_   int64  `thrift:"newEndClass,9,required" frugal:"9,required,i64" json:"newEndClass"`
	NewLocation_   string `thrift:"newLocation,10,required" frugal:"10,required,string" json:"newLocation"`
}

func NewCourseAdjustRule() *CourseAdjustRule {
	return &CourseAdjustRule{}
}

func (p *CourseAdjustRule) InitDefault() {
}

func (p *CourseAdjustRule) GetOldWeek() (v int64) {
	return p.OldWeek
}

func (p *CourseAdjustRule) GetOldDay() (v int64) {
	return p.OldDay
}

func (p *CourseAdjustRule) GetOldStartClass() (v int64) {
	return p.OldStartClass
}

func (p *CourseAdjustRule) GetOldEndClass() (v int64) {
	return p.OldEndClass
}

func (p *CourseAdjustRule) GetCanceled() (v bool) {
	return p.Canceled
}

func (p *CourseAdjustRule) GetNewWeek_() (v int64) {
	return p.NewWeek_
}

func (p *CourseAdjustRule) GetNewDay_() (v int64) {
	return p.NewDay_
}

func (p *CourseAdjustRule) GetNewStartClass_() (v int64) {
	return p.NewStartClass_
}

func (p *CourseAdjustRule) GetNewEndClass_() (v int64) {
	return p.NewEndClass_
}

func (p *CourseAdjustRule) GetNewLocation_() (v string) {
	return p.NewLocation_
}
func (p *CourseAdjustRule) SetOldWeek(val int64) {
	p.OldWeek = val
}
func (p *CourseAdjustRule) SetOldDay(val int64) {
	p.OldDay = val
}
func (p *CourseAdjustRule) SetOldStartClass(val int64) {
	p.OldStartClass = val
}
func (p *CourseAdjustRule) SetOldEndClass(val int64) {
	p.OldEndClass = val
}
func (p *CourseAdjustRule) SetCanceled(val bool) {
	p.Canceled = val
}
func (p *CourseAdjustRule) SetNewWeek_(val int64) {
	p.NewWeek_ = val
}
func (p *CourseAdjustRule) SetNewDay_(val int64) {
	p.NewDay_ = val
}
func (p *CourseAdjustRule) SetNewStartClass_(val int64) {
	p.NewStartClass_ = val
}
func (p *CourseAdjustRule) SetNewEndClass_(val int64) {
	p.NewEndClass_ = val
}
func (p *CourseAdjustRule) SetNewLocation_(val string) {
	p.NewLocation_ = val
}

func (p *CourseAdjustRule) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseAdjustRule(%+v)", *p)
}

type Course struct {
	Name             string                `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Teacher          string                `thrift:"teacher,2,required" frugal:"2,required,string" json:"teacher"`
	ScheduleRules    []*CourseScheduleRule `thrift:"scheduleRules,3,required" frugal:"3,required,list<CourseScheduleRule>" json:"scheduleRules"`
	AdjustRules      []*CourseAdjustRule   `thrift:"adjustRules,4,required" frugal:"4,required,list<CourseAdjustRule>" json:"adjustRules"`
	Remark           string                `thrift:"remark,5,required" frugal:"5,required,string" json:"remark"`
	Lessonplan       string                `thrift:"lessonplan,6,required" frugal:"6,required,string" json:"lessonplan"`
	Syllabus         string                `thrift:"syllabus,7,required" frugal:"7,required,string" json:"syllabus"`
	RawScheduleRules string                `thrift:"rawScheduleRules,8,required" frugal:"8,required,string" json:"rawScheduleRules"`
	RawAdjust        string                `thrift:"rawAdjust,9,required" frugal:"9,required,string" json:"rawAdjust"`
	ExamType         string                `thrift:"examType,10,required" frugal:"10,required,string" json:"examType"`
	ElectiveType     string                `thrift:"electiveType,11,required" frugal:"11,required,string" json:"electiveType"`
}

func NewCourse() *Course {
	return &Course{}
}

func (p *Course) InitDefault() {
}

func (p *Course) GetName() (v string) {
	return p.Name
}

func (p *Course) GetTeacher() (v string) {
	return p.Teacher
}

func (p *Course) GetScheduleRules() (v []*CourseScheduleRule) {
	return p.ScheduleRules
}

func (p *Course) GetAdjustRules() (v []*CourseAdjustRule) {
	return p.AdjustRules
}

func (p *Course) GetRemark() (v string) {
	return p.Remark
}

func (p *Course) GetLessonplan() (v string) {
	return p.Lessonplan
}

func (p *Course) GetSyllabus() (v string) {
	return p.Syllabus
}

func (p *Course) GetRawScheduleRules() (v string) {
	return p.RawScheduleRules
}

func (p *Course) GetRawAdjust() (v string) {
	return p.RawAdjust
}

func (p *Course) GetExamType() (v string) {
	return p.ExamType
}

func (p *Course) GetElectiveType() (v string) {
	return p.ElectiveType
}
func (p *Course) SetName(val string) {
	p.Name = val
}
func (p *Course) SetTeacher(val string) {
	p.Teacher = val
}
func (p *Course) SetScheduleRules(val []*CourseScheduleRule) {
	p.ScheduleRules = val
}
func (p *Course) SetAdjustRules(val []*CourseAdjustRule) {
	p.AdjustRules = val
}
func (p *Course) SetRemark(val string) {
	p.Remark = val
}
func (p *Course) SetLessonplan(val string) {
	p.Lessonplan = val
}
func (p *Course) SetSyllabus(val string) {
	p.Syllabus = val
}
func (p *Course) SetRawScheduleRules(val string) {
	p.RawScheduleRules = val
}
func (p *Course) SetRawAdjust(val string) {
	p.RawAdjust = val
}
func (p *Course) SetExamType(val string) {
	p.ExamType = val
}
func (p *Course) SetElectiveType(val string) {
	p.ElectiveType = val
}

func (p *Course) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Course(%+v)", *p)
}

type LocateDate struct {
	Week string `thrift:"week,1,required" frugal:"1,required,string" json:"week"`
	Year string `thrift:"year,2,required" frugal:"2,required,string" json:"year"`
	Term string `thrift:"term,3,required" frugal:"3,required,string" json:"term"`
	Date string `thrift:"date,4,required" frugal:"4,required,string" json:"date"`
}

func NewLocateDate() *LocateDate {
	return &LocateDate{}
}

func (p *LocateDate) InitDefault() {
}

func (p *LocateDate) GetWeek() (v string) {
	return p.Week
}

func (p *LocateDate) GetYear() (v string) {
	return p.Year
}

func (p *LocateDate) GetTerm() (v string) {
	return p.Term
}

func (p *LocateDate) GetDate() (v string) {
	return p.Date
}
func (p *LocateDate) SetWeek(val string) {
	p.Week = val
}
func (p *LocateDate) SetYear(val string) {
	p.Year = val
}
func (p *LocateDate) SetTerm(val string) {
	p.Term = val
}
func (p *LocateDate) SetDate(val string) {
	p.Date = val
}

func (p *LocateDate) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LocateDate(%+v)", *p)
}

type AdjustCourse struct {
	Id          int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Enabled     bool   `thrift:"enabled,2,required" frugal:"2,required,bool" json:"enabled"`
	Year        string `thrift:"year,3,required" frugal:"3,required,string" json:"year"`
	Term        string `thrift:"term,4,required" frugal:"4,required,string" json:"term"`
	FromDate    string `thrift:"from_date,5,required" frugal:"5,required,string" json:"from_date"`
	FromWeek    int64  `thrift:"from_week,6,required" frugal:"6,required,i64" json:"from_week"`
	FromWeekday int64  `thrift:"from_weekday,7,required" frugal:"7,required,i64" json:"from_weekday"`
	ToDate      string `thrift:"to_date,8,required" frugal:"8,required,string" json:"to_date"`
	ToWeek      int64  `thrift:"to_week,9,required" frugal:"9,required,i64" json:"to_week"`
	ToWeekday   int64  `thrift:"to_weekday,10,required" frugal:"10,required,i64" json:"to_weekday"`
}

func NewAdjustCourse() *AdjustCourse {
	return &AdjustCourse{}
}

func (p *AdjustCourse) InitDefault() {
}

func (p *AdjustCourse) GetId() (v int64) {
	return p.Id
}

func (p *AdjustCourse) GetEnabled() (v bool) {
	return p.Enabled
}

func (p *AdjustCourse) GetYear() (v string) {
	return p.Year
}

func (p *AdjustCourse) GetTerm() (v string) {
	return p.Term
}

func (p *AdjustCourse) GetFromDate() (v string) {
	return p.FromDate
}

func (p *AdjustCourse) GetFromWeek() (v int64) {
	return p.FromWeek
}

func (p *AdjustCourse) GetFromWeekday() (v int64) {
	return p.FromWeekday
}

func (p *AdjustCourse) GetToDate() (v string) {
	return p.ToDate
}

func (p *AdjustCourse) GetToWeek() (v int64) {
	return p.ToWeek
}

func (p *AdjustCourse) GetToWeekday() (v int64) {
	return p.ToWeekday
}
func (p *AdjustCourse) SetId(val int64) {
	p.Id = val
}
func (p *AdjustCourse) SetEnabled(val bool) {
	p.Enabled = val
}
func (p *AdjustCourse) SetYear(val string) {
	p.Year = val
}
func (p *AdjustCourse) SetTerm(val string) {
	p.Term = val
}
func (p *AdjustCourse) SetFromDate(val string) {
	p.FromDate = val
}
func (p *AdjustCourse) SetFromWeek(val int64) {
	p.FromWeek = val
}
func (p *AdjustCourse) SetFromWeekday(val int64) {
	p.FromWeekday = val
}
func (p *AdjustCourse) SetToDate(val string) {
	p.ToDate = val
}
func (p *AdjustCourse) SetToWeek(val int64) {
	p.ToWeek = val
}
func (p *AdjustCourse) SetToWeekday(val int64) {
	p.ToWeekday = val
}

func (p *AdjustCourse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdjustCourse(%+v)", *p)
}

type Picture struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Url        string `thrift:"url,3" frugal:"3,default,string" json:"url"`
	Href       string `thrift:"href,4" frugal:"4,default,string" json:"href"`
	Text       string `thrift:"text,5" frugal:"5,default,string" json:"text"`
	Type       int64  `thrift:"type,6" frugal:"6,default,i64" json:"type"`
	ShowTimes  *int64 `thrift:"show_times,7,optional" frugal:"7,optional,i64" json:"show_times,omitempty"`
	PointTimes *int64 `thrift:"point_times,8,optional" frugal:"8,optional,i64" json:"point_times,omitempty"`
	Duration   int64  `thrift:"duration,9" frugal:"9,default,i64" json:"duration"`
	SType      *int64 `thrift:"s_type,10,optional" frugal:"10,optional,i64" json:"s_type,omitempty"`
	Frequency  int64  `thrift:"frequency,11" frugal:"11,default,i64" json:"frequency"`
	StartAt    int64  `thrift:"start_at,12" frugal:"12,default,i64" json:"start_at"`
	EndAt      int64  `thrift:"end_at,13" frugal:"13,default,i64" json:"end_at"`
	StartTime  int64  `thrift:"start_time,14" frugal:"14,default,i64" json:"start_time"`
	EndTime    int64  `thrift:"end_time,15" frugal:"15,default,i64" json:"end_time"`
	Regex      string `thrift:"regex,16" frugal:"16,default,string" json:"regex"`
}

func NewPicture() *Picture {
	return &Picture{}
}

func (p *Picture) InitDefault() {
}

func (p *Picture) GetId() (v int64) {
	return p.Id
}

func (p *Picture) GetUrl() (v string) {
	return p.Url
}

func (p *Picture) GetHref() (v string) {
	return p.Href
}

func (p *Picture) GetText() (v string) {
	return p.Text
}

func (p *Picture) GetType() (v int64) {
	return p.Type
}

var Picture_ShowTimes_DEFAULT int64

func (p *Picture) GetShowTimes() (v int64) {
	if !p.IsSetShowTimes() {
		return Picture_ShowTimes_DEFAULT
	}
	return *p.ShowTimes
}

var Picture_PointTimes_DEFAULT int64

func (p *Picture) GetPointTimes() (v int64) {
	if !p.IsSetPointTimes() {
		return Picture_PointTimes_DEFAULT
	}
	return *p.PointTimes
}

func (p *Picture) GetDuration() (v int64) {
	return p.Duration
}

var Picture_SType_DEFAULT int64

func (p *Picture) GetSType() (v int64) {
	if !p.IsSetSType() {
		return Picture_SType_DEFAULT
	}
	return *p.SType
}

func (p *Picture) GetFrequency() (v int64) {
	return p.Frequency
}

func (p *Picture) GetStartAt() (v int64) {
	return p.StartAt
}

func (p *Picture) GetEndAt() (v int64) {
	return p.EndAt
}

func (p *Picture) GetStartTime() (v int64) {
	return p.StartTime
}

func (p *Picture) GetEndTime() (v int64) {
	return p.EndTime
}

func (p *Picture) GetRegex() (v string) {
	return p.Regex
}
func (p *Picture) SetId(val int64) {
	p.Id = val
}
func (p *Picture) SetUrl(val string) {
	p.Url = val
}
func (p *Picture) SetHref(val string) {
	p.Href = val
}
func (p *Picture) SetText(val string) {
	p.Text = val
}
func (p *Picture) SetType(val int64) {
	p.Type = val
}
func (p *Picture) SetShowTimes(val *int64) {
	p.ShowTimes = val
}
func (p *Picture) SetPointTimes(val *int64) {
	p.PointTimes = val
}
func (p *Picture) SetDuration(val int64) {
	p.Duration = val
}
func (p *Picture) SetSType(val *int64) {
	p.SType = val
}
func (p *Picture) SetFrequency(val int64) {
	p.Frequency = val
}
func (p *Picture) SetStartAt(val int64) {
	p.StartAt = val
}
func (p *Picture) SetEndAt(val int64) {
	p.EndAt = val
}
func (p *Picture) SetStartTime(val int64) {
	p.StartTime = val
}
func (p *Picture) SetEndTime(val int64) {
	p.EndTime = val
}
func (p *Picture) SetRegex(val string) {
	p.Regex = val
}

func (p *Picture) IsSetShowTimes() bool {
	return p.ShowTimes != nil
}

func (p *Picture) IsSetPointTimes() bool {
	return p.PointTimes != nil
}

func (p *Picture) IsSetSType() bool {
	return p.SType != nil
}

func (p *Picture) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Picture(%+v)", *p)
}

type UpYunFileDir struct {
	BasePath *string  `thrift:"basePath,1,optional" frugal:"1,optional,string" json:"basePath,omitempty"`
	Files    []string `thrift:"files,2,required" frugal:"2,required,list<string>" json:"files"`
	Folders  []string `thrift:"folders,3,required" frugal:"3,required,list<string>" json:"folders"`
}

func NewUpYunFileDir() *UpYunFileDir {
	return &UpYunFileDir{}
}

func (p *UpYunFileDir) InitDefault() {
}

var UpYunFileDir_BasePath_DEFAULT string

func (p *UpYunFileDir) GetBasePath() (v string) {
	if !p.IsSetBasePath() {
		return UpYunFileDir_BasePath_DEFAULT
	}
	return *p.BasePath
}

func (p *UpYunFileDir) GetFiles() (v []string) {
	return p.Files
}

func (p *UpYunFileDir) GetFolders() (v []string) {
	return p.Folders
}
func (p *UpYunFileDir) SetBasePath(val *string) {
	p.BasePath = val
}
func (p *UpYunFileDir) SetFiles(val []string) {
	p.Files = val
}
func (p *UpYunFileDir) SetFolders(val []string) {
	p.Folders = val
}

func (p *UpYunFileDir) IsSetBasePath() bool {
	return p.BasePath != nil
}

func (p *UpYunFileDir) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpYunFileDir(%+v)", *p)
}

type Score struct {
	Credit       string `thrift:"credit,1,required" frugal:"1,required,string" json:"credit"`
	Gpa          string `thrift:"gpa,2,required" frugal:"2,required,string" json:"gpa"`
	Name         string `thrift:"name,3,required" frugal:"3,required,string" json:"name"`
	Score        string `thrift:"score,4,required" frugal:"4,required,string" json:"score"`
	Teacher      string `thrift:"teacher,5,required" frugal:"5,required,string" json:"teacher"`
	Term         string `thrift:"term,6,required" frugal:"6,required,string" json:"term"`
	ExamType     string `thrift:"exam_type,7,required" frugal:"7,required,string" json:"exam_type"`
	ElectiveType string `thrift:"elective_type,8,required" frugal:"8,required,string" json:"elective_type"`
	Classroom    string `thrift:"classroom,9,required" frugal:"9,required,string" json:"classroom"`
}

func NewScore() *Score {
	return &Score{}
}

func (p *Score) InitDefault() {
}

func (p *Score) GetCredit() (v string) {
	return p.Credit
}

func (p *Score) GetGpa() (v string) {
	return p.Gpa
}

func (p *Score) GetName() (v string) {
	return p.Name
}

func (p *Score) GetScore() (v string) {
	return p.Score
}

func (p *Score) GetTeacher() (v string) {
	return p.Teacher
}

func (p *Score) GetTerm() (v string) {
	return p.Term
}

func (p *Score) GetExamType() (v string) {
	return p.ExamType
}

func (p *Score) GetElectiveType() (v string) {
	return p.ElectiveType
}

func (p *Score) GetClassroom() (v string) {
	return p.Classroom
}
func (p *Score) SetCredit(val string) {
	p.Credit = val
}
func (p *Score) SetGpa(val string) {
	p.Gpa = val
}
func (p *Score) SetName(val string) {
	p.Name = val
}
func (p *Score) SetScore(val string) {
	p.Score = val
}
func (p *Score) SetTeacher(val string) {
	p.Teacher = val
}
func (p *Score) SetTerm(val string) {
	p.Term = val
}
func (p *Score) SetExamType(val string) {
	p.ExamType = val
}
func (p *Score) SetElectiveType(val string) {
	p.ElectiveType = val
}
func (p *Score) SetClassroom(val string) {
	p.Classroom = val
}

func (p *Score) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Score(%+v)", *p)
}

type GPABean struct {
	Time string     `thrift:"time,1,required" frugal:"1,required,string" json:"time"`
	Data []*GPAData `thrift:"data,2,required" frugal:"2,required,list<GPAData>" json:"data"`
}

func NewGPABean() *GPABean {
	return &GPABean{}
}

func (p *GPABean) InitDefault() {
}

func (p *GPABean) GetTime() (v string) {
	return p.Time
}

func (p *GPABean) GetData() (v []*GPAData) {
	return p.Data
}
func (p *GPABean) SetTime(val string) {
	p.Time = val
}
func (p *GPABean) SetData(val []*GPAData) {
	p.Data = val
}

func (p *GPABean) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GPABean(%+v)", *p)
}

type GPAData struct {
	Type  string `thrift:"type,1,required" frugal:"1,required,string" json:"type"`
	Value string `thrift:"value,2,required" frugal:"2,required,string" json:"value"`
}

func NewGPAData() *GPAData {
	return &GPAData{}
}

func (p *GPAData) InitDefault() {
}

func (p *GPAData) GetType() (v string) {
	return p.Type
}

func (p *GPAData) GetValue() (v string) {
	return p.Value
}
func (p *GPAData) SetType(val string) {
	p.Type = val
}
func (p *GPAData) SetValue(val string) {
	p.Value = val
}

func (p *GPAData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GPAData(%+v)", *p)
}

type Credit struct {
	Type  string `thrift:"type,1,required" frugal:"1,required,string" json:"type"`
	Gain  string `thrift:"gain,2,required" frugal:"2,required,string" json:"gain"`
	Total string `thrift:"total,3,required" frugal:"3,required,string" json:"total"`
}

func NewCredit() *Credit {
	return &Credit{}
}

func (p *Credit) InitDefault() {
}

func (p *Credit) GetType() (v string) {
	return p.Type
}

func (p *Credit) GetGain() (v string) {
	return p.Gain
}

func (p *Credit) GetTotal() (v string) {
	return p.Total
}
func (p *Credit) SetType(val string) {
	p.Type = val
}
func (p *Credit) SetGain(val string) {
	p.Gain = val
}
func (p *Credit) SetTotal(val string) {
	p.Total = val
}

func (p *Credit) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Credit(%+v)", *p)
}

type UnifiedExam struct {
	Name  string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Score string `thrift:"score,2,required" frugal:"2,required,string" json:"score"`
	Term  string `thrift:"term,3,required" frugal:"3,required,string" json:"term"`
}

func NewUnifiedExam() *UnifiedExam {
	return &UnifiedExam{}
}

func (p *UnifiedExam) InitDefault() {
}

func (p *UnifiedExam) GetName() (v string) {
	return p.Name
}

func (p *UnifiedExam) GetScore() (v string) {
	return p.Score
}

func (p *UnifiedExam) GetTerm() (v string) {
	return p.Term
}
func (p *UnifiedExam) SetName(val string) {
	p.Name = val
}
func (p *UnifiedExam) SetScore(val string) {
	p.Score = val
}
func (p *UnifiedExam) SetTerm(val string) {
	p.Term = val
}

func (p *UnifiedExam) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnifiedExam(%+v)", *p)
}

type CreditDetail struct {
	Key   string `thrift:"key,1,required" frugal:"1,required,string" json:"key"`
	Value string `thrift:"value,2,required" frugal:"2,required,string" json:"value"`
}

func NewCreditDetail() *CreditDetail {
	return &CreditDetail{}
}

func (p *CreditDetail) InitDefault() {
}

func (p *CreditDetail) GetKey() (v string) {
	return p.Key
}

func (p *CreditDetail) GetValue() (v string) {
	return p.Value
}
func (p *CreditDetail) SetKey(val string) {
	p.Key = val
}
func (p *CreditDetail) SetValue(val string) {
	p.Value = val
}

func (p *CreditDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreditDetail(%+v)", *p)
}

type CreditCategory struct {
	Type string          `thrift:"type,1,required" frugal:"1,required,string" json:"type"`
	Data []*CreditDetail `thrift:"data,2,required" frugal:"2,required,list<CreditDetail>" json:"data"`
}

func NewCreditCategory() *CreditCategory {
	return &CreditCategory{}
}

func (p *CreditCategory) InitDefault() {
}

func (p *CreditCategory) GetType() (v string) {
	return p.Type
}

func (p *CreditCategory) GetData() (v []*CreditDetail) {
	return p.Data
}
func (p *CreditCategory) SetType(val string) {
	p.Type = val
}
func (p *CreditCategory) SetData(val []*CreditDetail) {
	p.Data = val
}

func (p *CreditCategory) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreditCategory(%+v)", *p)
}

type PaperData struct {
	BasePath *string  `thrift:"base_path,1,optional" frugal:"1,optional,string" json:"base_path,omitempty"`
	Files    []string `thrift:"files,2,required" frugal:"2,required,list<string>" json:"files"`
	Folders  []string `thrift:"folders,3,required" frugal:"3,required,list<string>" json:"folders"`
}

func NewPaperData() *PaperData {
	return &PaperData{}
}

func (p *PaperData) InitDefault() {
}

var PaperData_BasePath_DEFAULT string

func (p *PaperData) GetBasePath() (v string) {
	if !p.IsSetBasePath() {
		return PaperData_BasePath_DEFAULT
	}
	return *p.BasePath
}

func (p *PaperData) GetFiles() (v []string) {
	return p.Files
}

func (p *PaperData) GetFolders() (v []string) {
	return p.Folders
}
func (p *PaperData) SetBasePath(val *string) {
	p.BasePath = val
}
func (p *PaperData) SetFiles(val []string) {
	p.Files = val
}
func (p *PaperData) SetFolders(val []string) {
	p.Folders = val
}

func (p *PaperData) IsSetBasePath() bool {
	return p.BasePath != nil
}

func (p *PaperData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaperData(%+v)", *p)
}

type PaperUrlData struct {
	Url string `thrift:"url,1,required" frugal:"1,required,string" json:"url"`
}

func NewPaperUrlData() *PaperUrlData {
	return &PaperUrlData{}
}

func (p *PaperUrlData) InitDefault() {
}

func (p *PaperUrlData) GetUrl() (v string) {
	return p.Url
}
func (p *PaperUrlData) SetUrl(val string) {
	p.Url = val
}

func (p *PaperUrlData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaperUrlData(%+v)", *p)
}

type Term struct {
	TermId     *string `thrift:"term_id,1,optional" frugal:"1,optional,string" json:"term_id,omitempty"`
	SchoolYear *string `thrift:"school_year,2,optional" frugal:"2,optional,string" json:"school_year,omitempty"`
	Term       *string `thrift:"term,3,optional" frugal:"3,optional,string" json:"term,omitempty"`
	StartDate  *string `thrift:"start_date,4,optional" frugal:"4,optional,string" json:"start_date,omitempty"`
	EndDate    *string `thrift:"end_date,5,optional" frugal:"5,optional,string" json:"end_date,omitempty"`
}

func NewTerm() *Term {
	return &Term{}
}

func (p *Term) InitDefault() {
}

var Term_TermId_DEFAULT string

func (p *Term) GetTermId() (v string) {
	if !p.IsSetTermId() {
		return Term_TermId_DEFAULT
	}
	return *p.TermId
}

var Term_SchoolYear_DEFAULT string

func (p *Term) GetSchoolYear() (v string) {
	if !p.IsSetSchoolYear() {
		return Term_SchoolYear_DEFAULT
	}
	return *p.SchoolYear
}

var Term_Term_DEFAULT string

func (p *Term) GetTerm() (v string) {
	if !p.IsSetTerm() {
		return Term_Term_DEFAULT
	}
	return *p.Term
}

var Term_StartDate_DEFAULT string

func (p *Term) GetStartDate() (v string) {
	if !p.IsSetStartDate() {
		return Term_StartDate_DEFAULT
	}
	return *p.StartDate
}

var Term_EndDate_DEFAULT string

func (p *Term) GetEndDate() (v string) {
	if !p.IsSetEndDate() {
		return Term_EndDate_DEFAULT
	}
	return *p.EndDate
}
func (p *Term) SetTermId(val *string) {
	p.TermId = val
}
func (p *Term) SetSchoolYear(val *string) {
	p.SchoolYear = val
}
func (p *Term) SetTerm(val *string) {
	p.Term = val
}
func (p *Term) SetStartDate(val *string) {
	p.StartDate = val
}
func (p *Term) SetEndDate(val *string) {
	p.EndDate = val
}

func (p *Term) IsSetTermId() bool {
	return p.TermId != nil
}

func (p *Term) IsSetSchoolYear() bool {
	return p.SchoolYear != nil
}

func (p *Term) IsSetTerm() bool {
	return p.Term != nil
}

func (p *Term) IsSetStartDate() bool {
	return p.StartDate != nil
}

func (p *Term) IsSetEndDate() bool {
	return p.EndDate != nil
}

func (p *Term) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Term(%+v)", *p)
}

type TermEvent struct {
	Name      *string `thrift:"name,1,optional" frugal:"1,optional,string" json:"name,omitempty"`
	StartDate *string `thrift:"start_date,2,optional" frugal:"2,optional,string" json:"start_date,omitempty"`
	EndDate   *string `thrift:"end_date,3,optional" frugal:"3,optional,string" json:"end_date,omitempty"`
}

func NewTermEvent() *TermEvent {
	return &TermEvent{}
}

func (p *TermEvent) InitDefault() {
}

var TermEvent_Name_DEFAULT string

func (p *TermEvent) GetName() (v string) {
	if !p.IsSetName() {
		return TermEvent_Name_DEFAULT
	}
	return *p.Name
}

var TermEvent_StartDate_DEFAULT string

func (p *TermEvent) GetStartDate() (v string) {
	if !p.IsSetStartDate() {
		return TermEvent_StartDate_DEFAULT
	}
	return *p.StartDate
}

var TermEvent_EndDate_DEFAULT string

func (p *TermEvent) GetEndDate() (v string) {
	if !p.IsSetEndDate() {
		return TermEvent_EndDate_DEFAULT
	}
	return *p.EndDate
}
func (p *TermEvent) SetName(val *string) {
	p.Name = val
}
func (p *TermEvent) SetStartDate(val *string) {
	p.StartDate = val
}
func (p *TermEvent) SetEndDate(val *string) {
	p.EndDate = val
}

func (p *TermEvent) IsSetName() bool {
	return p.Name != nil
}

func (p *TermEvent) IsSetStartDate() bool {
	return p.StartDate != nil
}

func (p *TermEvent) IsSetEndDate() bool {
	return p.EndDate != nil
}

func (p *TermEvent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TermEvent(%+v)", *p)
}

type TermList struct {
	CurrentTerm *string `thrift:"current_term,1,optional" frugal:"1,optional,string" json:"current_term,omitempty"`
	Terms       []*Term `thrift:"terms,2,optional" frugal:"2,optional,list<Term>" json:"terms,omitempty"`
}

func NewTermList() *TermList {
	return &TermList{}
}

func (p *TermList) InitDefault() {
}

var TermList_CurrentTerm_DEFAULT string

func (p *TermList) GetCurrentTerm() (v string) {
	if !p.IsSetCurrentTerm() {
		return TermList_CurrentTerm_DEFAULT
	}
	return *p.CurrentTerm
}

var TermList_Terms_DEFAULT []*Term

func (p *TermList) GetTerms() (v []*Term) {
	if !p.IsSetTerms() {
		return TermList_Terms_DEFAULT
	}
	return p.Terms
}
func (p *TermList) SetCurrentTerm(val *string) {
	p.CurrentTerm = val
}
func (p *TermList) SetTerms(val []*Term) {
	p.Terms = val
}

func (p *TermList) IsSetCurrentTerm() bool {
	return p.CurrentTerm != nil
}

func (p *TermList) IsSetTerms() bool {
	return p.Terms != nil
}

func (p *TermList) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TermList(%+v)", *p)
}

type TermInfo struct {
	TermId     *string      `thrift:"term_id,1,optional" frugal:"1,optional,string" json:"term_id,omitempty"`
	Term       *string      `thrift:"term,2,optional" frugal:"2,optional,string" json:"term,omitempty"`
	SchoolYear *string      `thrift:"school_year,3,optional" frugal:"3,optional,string" json:"school_year,omitempty"`
	Events     []*TermEvent `thrift:"events,4,optional" frugal:"4,optional,list<TermEvent>" json:"events,omitempty"`
}

func NewTermInfo() *TermInfo {
	return &TermInfo{}
}

func (p *TermInfo) InitDefault() {
}

var TermInfo_TermId_DEFAULT string

func (p *TermInfo) GetTermId() (v string) {
	if !p.IsSetTermId() {
		return TermInfo_TermId_DEFAULT
	}
	return *p.TermId
}

var TermInfo_Term_DEFAULT string

func (p *TermInfo) GetTerm() (v string) {
	if !p.IsSetTerm() {
		return TermInfo_Term_DEFAULT
	}
	return *p.Term
}

var TermInfo_SchoolYear_DEFAULT string

func (p *TermInfo) GetSchoolYear() (v string) {
	if !p.IsSetSchoolYear() {
		return TermInfo_SchoolYear_DEFAULT
	}
	return *p.SchoolYear
}

var TermInfo_Events_DEFAULT []*TermEvent

func (p *TermInfo) GetEvents() (v []*TermEvent) {
	if !p.IsSetEvents() {
		return TermInfo_Events_DEFAULT
	}
	return p.Events
}
func (p *TermInfo) SetTermId(val *string) {
	p.TermId = val
}
func (p *TermInfo) SetTerm(val *string) {
	p.Term = val
}
func (p *TermInfo) SetSchoolYear(val *string) {
	p.SchoolYear = val
}
func (p *TermInfo) SetEvents(val []*TermEvent) {
	p.Events = val
}

func (p *TermInfo) IsSetTermId() bool {
	return p.TermId != nil
}

func (p *TermInfo) IsSetTerm() bool {
	return p.Term != nil
}

func (p *TermInfo) IsSetSchoolYear() bool {
	return p.SchoolYear != nil
}

func (p *TermInfo) IsSetEvents() bool {
	return p.Events != nil
}

func (p *TermInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TermInfo(%+v)", *p)
}

type NoticeInfo struct {
	Title *string `thrift:"title,1,optional" frugal:"1,optional,string" json:"title,omitempty"`
	Url   *string `thrift:"url,2,optional" frugal:"2,optional,string" json:"url,omitempty"`
	Date  *string `thrift:"date,3,optional" frugal:"3,optional,string" json:"date,omitempty"`
}

func NewNoticeInfo() *NoticeInfo {
	return &NoticeInfo{}
}

func (p *NoticeInfo) InitDefault() {
}

var NoticeInfo_Title_DEFAULT string

func (p *NoticeInfo) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return NoticeInfo_Title_DEFAULT
	}
	return *p.Title
}

var NoticeInfo_Url_DEFAULT string

func (p *NoticeInfo) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return NoticeInfo_Url_DEFAULT
	}
	return *p.Url
}

var NoticeInfo_Date_DEFAULT string

func (p *NoticeInfo) GetDate() (v string) {
	if !p.IsSetDate() {
		return NoticeInfo_Date_DEFAULT
	}
	return *p.Date
}
func (p *NoticeInfo) SetTitle(val *string) {
	p.Title = val
}
func (p *NoticeInfo) SetUrl(val *string) {
	p.Url = val
}
func (p *NoticeInfo) SetDate(val *string) {
	p.Date = val
}

func (p *NoticeInfo) IsSetTitle() bool {
	return p.Title != nil
}

func (p *NoticeInfo) IsSetUrl() bool {
	return p.Url != nil
}

func (p *NoticeInfo) IsSetDate() bool {
	return p.Date != nil
}

func (p *NoticeInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NoticeInfo(%+v)", *p)
}

type Contributor struct {
	Name          string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	AvatarUrl     string `thrift:"avatar_url,2" frugal:"2,default,string" json:"avatar_url"`
	Url           string `thrift:"url,3" frugal:"3,default,string" json:"url"`
	Contributions int64  `thrift:"contributions,4" frugal:"4,default,i64" json:"contributions"`
}

func NewContributor() *Contributor {
	return &Contributor{}
}

func (p *Contributor) InitDefault() {
}

func (p *Contributor) GetName() (v string) {
	return p.Name
}

func (p *Contributor) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *Contributor) GetUrl() (v string) {
	return p.Url
}

func (p *Contributor) GetContributions() (v int64) {
	return p.Contributions
}
func (p *Contributor) SetName(val string) {
	p.Name = val
}
func (p *Contributor) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *Contributor) SetUrl(val string) {
	p.Url = val
}
func (p *Contributor) SetContributions(val int64) {
	p.Contributions = val
}

func (p *Contributor) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Contributor(%+v)", *p)
}

type ToolboxConfig struct {
	ToolId   int64   `thrift:"tool_id,1,required" frugal:"1,required,i64" json:"tool_id"`
	Visible  *bool   `thrift:"visible,2,optional" frugal:"2,optional,bool" json:"visible,omitempty"`
	Name     *string `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	Icon     *string `thrift:"icon,4,optional" frugal:"4,optional,string" json:"icon,omitempty"`
	Type     *string `thrift:"type,5,optional" frugal:"5,optional,string" json:"type,omitempty"`
	Message  *string `thrift:"message,6,optional" frugal:"6,optional,string" json:"message,omitempty"`
	Extra    *string `thrift:"extra,7,optional" frugal:"7,optional,string" json:"extra,omitempty"`
	Platform *string `thrift:"platform,8,optional" frugal:"8,optional,string" json:"platform,omitempty"`
	Version  *int64  `thrift:"version,9,optional" frugal:"9,optional,i64" json:"version,omitempty"`
}

func NewToolboxConfig() *ToolboxConfig {
	return &ToolboxConfig{}
}

func (p *ToolboxConfig) InitDefault() {
}

func (p *ToolboxConfig) GetToolId() (v int64) {
	return p.ToolId
}

var ToolboxConfig_Visible_DEFAULT bool

func (p *ToolboxConfig) GetVisible() (v bool) {
	if !p.IsSetVisible() {
		return ToolboxConfig_Visible_DEFAULT
	}
	return *p.Visible
}

var ToolboxConfig_Name_DEFAULT string

func (p *ToolboxConfig) GetName() (v string) {
	if !p.IsSetName() {
		return ToolboxConfig_Name_DEFAULT
	}
	return *p.Name
}

var ToolboxConfig_Icon_DEFAULT string

func (p *ToolboxConfig) GetIcon() (v string) {
	if !p.IsSetIcon() {
		return ToolboxConfig_Icon_DEFAULT
	}
	return *p.Icon
}

var ToolboxConfig_Type_DEFAULT string

func (p *ToolboxConfig) GetType() (v string) {
	if !p.IsSetType() {
		return ToolboxConfig_Type_DEFAULT
	}
	return *p.Type
}

var ToolboxConfig_Message_DEFAULT string

func (p *ToolboxConfig) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return ToolboxConfig_Message_DEFAULT
	}
	return *p.Message
}

var ToolboxConfig_Extra_DEFAULT string

func (p *ToolboxConfig) GetExtra() (v string) {
	if !p.IsSetExtra() {
		return ToolboxConfig_Extra_DEFAULT
	}
	return *p.Extra
}

var ToolboxConfig_Platform_DEFAULT string

func (p *ToolboxConfig) GetPlatform() (v string) {
	if !p.IsSetPlatform() {
		return ToolboxConfig_Platform_DEFAULT
	}
	return *p.Platform
}

var ToolboxConfig_Version_DEFAULT int64

func (p *ToolboxConfig) GetVersion() (v int64) {
	if !p.IsSetVersion() {
		return ToolboxConfig_Version_DEFAULT
	}
	return *p.Version
}
func (p *ToolboxConfig) SetToolId(val int64) {
	p.ToolId = val
}
func (p *ToolboxConfig) SetVisible(val *bool) {
	p.Visible = val
}
func (p *ToolboxConfig) SetName(val *string) {
	p.Name = val
}
func (p *ToolboxConfig) SetIcon(val *string) {
	p.Icon = val
}
func (p *ToolboxConfig) SetType(val *string) {
	p.Type = val
}
func (p *ToolboxConfig) SetMessage(val *string) {
	p.Message = val
}
func (p *ToolboxConfig) SetExtra(val *string) {
	p.Extra = val
}
func (p *ToolboxConfig) SetPlatform(val *string) {
	p.Platform = val
}
func (p *ToolboxConfig) SetVersion(val *int64) {
	p.Version = val
}

func (p *ToolboxConfig) IsSetVisible() bool {
	return p.Visible != nil
}

func (p *ToolboxConfig) IsSetName() bool {
	return p.Name != nil
}

func (p *ToolboxConfig) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *ToolboxConfig) IsSetType() bool {
	return p.Type != nil
}

func (p *ToolboxConfig) IsSetMessage() bool {
	return p.Message != nil
}

func (p *ToolboxConfig) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *ToolboxConfig) IsSetPlatform() bool {
	return p.Platform != nil
}

func (p *ToolboxConfig) IsSetVersion() bool {
	return p.Version != nil
}

func (p *ToolboxConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolboxConfig(%+v)", *p)
}

type Version struct {
	VersionCode *string `thrift:"version_code,1,optional" frugal:"1,optional,string" json:"version_code,omitempty"`
	VersionName *string `thrift:"version_name,2,optional" frugal:"2,optional,string" json:"version_name,omitempty"`
	Force       *bool   `thrift:"force,3,optional" frugal:"3,optional,bool" json:"force,omitempty"`
	Changelog   *string `thrift:"changelog,4,optional" frugal:"4,optional,string" json:"changelog,omitempty"`
	Url         *string `thrift:"url,5,optional" frugal:"5,optional,string" json:"url,omitempty"`
}

func NewVersion() *Version {
	return &Version{}
}

func (p *Version) InitDefault() {
}

var Version_VersionCode_DEFAULT string

func (p *Version) GetVersionCode() (v string) {
	if !p.IsSetVersionCode() {
		return Version_VersionCode_DEFAULT
	}
	return *p.VersionCode
}

var Version_VersionName_DEFAULT string

func (p *Version) GetVersionName() (v string) {
	if !p.IsSetVersionName() {
		return Version_VersionName_DEFAULT
	}
	return *p.VersionName
}

var Version_Force_DEFAULT bool

func (p *Version) GetForce() (v bool) {
	if !p.IsSetForce() {
		return Version_Force_DEFAULT
	}
	return *p.Force
}

var Version_Changelog_DEFAULT string

func (p *Version) GetChangelog() (v string) {
	if !p.IsSetChangelog() {
		return Version_Changelog_DEFAULT
	}
	return *p.Changelog
}

var Version_Url_DEFAULT string

func (p *Version) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return Version_Url_DEFAULT
	}
	return *p.Url
}
func (p *Version) SetVersionCode(val *string) {
	p.VersionCode = val
}
func (p *Version) SetVersionName(val *string) {
	p.VersionName = val
}
func (p *Version) SetForce(val *bool) {
	p.Force = val
}
func (p *Version) SetChangelog(val *string) {
	p.Changelog = val
}
func (p *Version) SetUrl(val *string) {
	p.Url = val
}

func (p *Version) IsSetVersionCode() bool {
	return p.VersionCode != nil
}

func (p *Version) IsSetVersionName() bool {
	return p.VersionName != nil
}

func (p *Version) IsSetForce() bool {
	return p.Force != nil
}

func (p *Version) IsSetChangelog() bool {
	return p.Changelog != nil
}

func (p *Version) IsSetUrl() bool {
	return p.Url != nil
}

func (p *Version) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Version(%+v)", *p)
}

type Feedback struct {
	ReportId       int64  `thrift:"report_id,1,required" frugal:"1,required,i64" json:"report_id"`
	StuId          string `thrift:"stu_id,2,required" frugal:"2,required,string" json:"stu_id"`
	Name           string `thrift:"name,3,required" frugal:"3,required,string" json:"name"`
	College        string `thrift:"college,4,required" frugal:"4,required,string" json:"college"`
	ContactPhone   string `thrift:"contact_phone,5,required" frugal:"5,required,string" json:"contact_phone"`
	ContactQq      string `thrift:"contact_qq,6,required" frugal:"6,required,string" json:"contact_qq"`
	ContactEmail   string `thrift:"contact_email,7,required" frugal:"7,required,string" json:"contact_email"`
	NetworkEnv     string `thrift:"network_env,8,required" frugal:"8,required,string" json:"network_env"`
	IsOnCampus     bool   `thrift:"is_on_campus,9,required" frugal:"9,required,bool" json:"is_on_campus"`
	OsName         string `thrift:"os_name,10,required" frugal:"10,required,string" json:"os_name"`
	OsVersion      string `thrift:"os_version,11,required" frugal:"11,required,string" json:"os_version"`
	Manufacturer   string `thrift:"manufacturer,12,required" frugal:"12,required,string" json:"manufacturer"`
	DeviceModel    string `thrift:"device_model,13,required" frugal:"13,required,string" json:"device_model"`
	ProblemDesc    string `thrift:"problem_desc,14,required" frugal:"14,required,string" json:"problem_desc"`
	Screenshots    string `thrift:"screenshots,15,required" frugal:"15,required,string" json:"screenshots"`
	AppVersion     string `thrift:"app_version,16,required" frugal:"16,required,string" json:"app_version"`
	VersionHistory string `thrift:"version_history,17,required" frugal:"17,required,string" json:"version_history"`
	NetworkTraces  string `thrift:"network_traces,18,required" frugal:"18,required,string" json:"network_traces"`
	Events         string `thrift:"events,19,required" frugal:"19,required,string" json:"events"`
	UserSettings   string `thrift:"user_settings,20,required" frugal:"20,required,string" json:"user_settings"`
}

func NewFeedback() *Feedback {
	return &Feedback{}
}

func (p *Feedback) InitDefault() {
}

func (p *Feedback) GetReportId() (v int64) {
	return p.ReportId
}

func (p *Feedback) GetStuId() (v string) {
	return p.StuId
}

func (p *Feedback) GetName() (v string) {
	return p.Name
}

func (p *Feedback) GetCollege() (v string) {
	return p.College
}

func (p *Feedback) GetContactPhone() (v string) {
	return p.ContactPhone
}

func (p *Feedback) GetContactQq() (v string) {
	return p.ContactQq
}

func (p *Feedback) GetContactEmail() (v string) {
	return p.ContactEmail
}

func (p *Feedback) GetNetworkEnv() (v string) {
	return p.NetworkEnv
}

func (p *Feedback) GetIsOnCampus() (v bool) {
	return p.IsOnCampus
}

func (p *Feedback) GetOsName() (v string) {
	return p.OsName
}

func (p *Feedback) GetOsVersion() (v string) {
	return p.OsVersion
}

func (p *Feedback) GetManufacturer() (v string) {
	return p.Manufacturer
}

func (p *Feedback) GetDeviceModel() (v string) {
	return p.DeviceModel
}

func (p *Feedback) GetProblemDesc() (v string) {
	return p.ProblemDesc
}

func (p *Feedback) GetScreenshots() (v string) {
	return p.Screenshots
}

func (p *Feedback) GetAppVersion() (v string) {
	return p.AppVersion
}

func (p *Feedback) GetVersionHistory() (v string) {
	return p.VersionHistory
}

func (p *Feedback) GetNetworkTraces() (v string) {
	return p.NetworkTraces
}

func (p *Feedback) GetEvents() (v string) {
	return p.Events
}

func (p *Feedback) GetUserSettings() (v string) {
	return p.UserSettings
}
func (p *Feedback) SetReportId(val int64) {
	p.ReportId = val
}
func (p *Feedback) SetStuId(val string) {
	p.StuId = val
}
func (p *Feedback) SetName(val string) {
	p.Name = val
}
func (p *Feedback) SetCollege(val string) {
	p.College = val
}
func (p *Feedback) SetContactPhone(val string) {
	p.ContactPhone = val
}
func (p *Feedback) SetContactQq(val string) {
	p.ContactQq = val
}
func (p *Feedback) SetContactEmail(val string) {
	p.ContactEmail = val
}
func (p *Feedback) SetNetworkEnv(val string) {
	p.NetworkEnv = val
}
func (p *Feedback) SetIsOnCampus(val bool) {
	p.IsOnCampus = val
}
func (p *Feedback) SetOsName(val string) {
	p.OsName = val
}
func (p *Feedback) SetOsVersion(val string) {
	p.OsVersion = val
}
func (p *Feedback) SetManufacturer(val string) {
	p.Manufacturer = val
}
func (p *Feedback) SetDeviceModel(val string) {
	p.DeviceModel = val
}
func (p *Feedback) SetProblemDesc(val string) {
	p.ProblemDesc = val
}
func (p *Feedback) SetScreenshots(val string) {
	p.Screenshots = val
}
func (p *Feedback) SetAppVersion(val string) {
	p.AppVersion = val
}
func (p *Feedback) SetVersionHistory(val string) {
	p.VersionHistory = val
}
func (p *Feedback) SetNetworkTraces(val string) {
	p.NetworkTraces = val
}
func (p *Feedback) SetEvents(val string) {
	p.Events = val
}
func (p *Feedback) SetUserSettings(val string) {
	p.UserSettings = val
}

func (p *Feedback) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Feedback(%+v)", *p)
}

type FeedbackListItem struct {
	ReportId    int64  `thrift:"report_id,1,required" frugal:"1,required,i64" json:"report_id"`
	Name        string `thrift:"name,2,required" frugal:"2,required,string" json:"name"`
	NetworkEnv  string `thrift:"network_env,3,required" frugal:"3,required,string" json:"network_env"`
	ProblemDesc string `thrift:"problem_desc,4,required" frugal:"4,required,string" json:"problem_desc"`
	AppVersion  string `thrift:"app_version,6,required" frugal:"6,required,string" json:"app_version"`
}

func NewFeedbackListItem() *FeedbackListItem {
	return &FeedbackListItem{}
}

func (p *FeedbackListItem) InitDefault() {
}

func (p *FeedbackListItem) GetReportId() (v int64) {
	return p.ReportId
}

func (p *FeedbackListItem) GetName() (v string) {
	return p.Name
}

func (p *FeedbackListItem) GetNetworkEnv() (v string) {
	return p.NetworkEnv
}

func (p *FeedbackListItem) GetProblemDesc() (v string) {
	return p.ProblemDesc
}

func (p *FeedbackListItem) GetAppVersion() (v string) {
	return p.AppVersion
}
func (p *FeedbackListItem) SetReportId(val int64) {
	p.ReportId = val
}
func (p *FeedbackListItem) SetName(val string) {
	p.Name = val
}
func (p *FeedbackListItem) SetNetworkEnv(val string) {
	p.NetworkEnv = val
}
func (p *FeedbackListItem) SetProblemDesc(val string) {
	p.ProblemDesc = val
}
func (p *FeedbackListItem) SetAppVersion(val string) {
	p.AppVersion = val
}

func (p *FeedbackListItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedbackListItem(%+v)", *p)
}
