system:
  domain: "classroom"
  host: "0.0.0.0"
  port: "20002"


redis:
  redisHost: "fzu-helper-redis"
  redisPort: "6379"
  redisPassword: "fzu-helper"
  redisDbName: 0


etcd:
  etcdHost: "etcd"
  etcdPort: "2379"
