/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/west2-online/fzuhelper-server/api/model/api"
	"github.com/west2-online/fzuhelper-server/api/pack"
	"github.com/west2-online/fzuhelper-server/api/rpc"
	"github.com/west2-online/fzuhelper-server/kitex_gen/admin"
	"github.com/west2-online/fzuhelper-server/pkg/constants"
	"github.com/west2-online/fzuhelper-server/pkg/errno"
)

// AuthMe .
// @router /api/v1/admin/auth/me [GET]
func AuthMe(ctx context.Context, c *app.RequestContext) {
	id, ok := c.Get(constants.AdminIDContextKey)
	if !ok {
		pack.RespError(c, errno.AuthError)
		return
	}
	adminID := id.(string)
	resp := new(api.AuthMeResponse)
	resp.AdminID = &adminID
	pack.RespData(c, resp)
}

// SSOLogin .
// @router /api/v1/admin/auth/login [GET]
func SSOLogin(ctx context.Context, c *app.RequestContext) {
	var req api.SSOLoginRequest
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	authorizeUrl, err := rpc.SSOLoginRPC(ctx, &admin.LoginRequest{ReturnTo: req.ReturnTo})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	c.Redirect(consts.StatusFound, []byte(authorizeUrl))
}

// Callback .
// @router /api/v1/admin/auth/callback [GET]
func Callback(ctx context.Context, c *app.RequestContext) {
	var req api.CallbackRequest
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	redirectUrl, err := rpc.AdminCallbackRPC(ctx, &admin.CallbackRequest{
		State: req.State,
		Code:  req.Code,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}
	c.Redirect(consts.StatusFound, []byte(redirectUrl))
}

// Exchange .
// @router /api/v1/admin/auth/exchange [POST]
func Exchange(ctx context.Context, c *app.RequestContext) {
	var req api.ExchangeRequest
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(c, errno.ParamError.WithError(err))
		return
	}

	accessToken, err := rpc.AdminExchangeTicketRPC(ctx, &admin.ExchangeTicketRequest{
		Ticket: req.Ticket,
	})
	if err != nil {
		pack.RespError(c, err)
		return
	}

	resp := new(api.ExchangeResponse)
	resp.AccessToken = &accessToken
	pack.RespData(c, resp)
}

// Logout .
// @router /api/v1/admin/auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AdminLogoutRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AdminLogoutResponse)

	c.JSON(consts.StatusOK, resp)
}
