/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/west2-online/fzuhelper-server/api/handler"
	"github.com/west2-online/fzuhelper-server/api/handler/api"
	"github.com/west2-online/fzuhelper-server/api/handler/custom"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 20241016兼容-2024肖垲
	/*
		旧的福uu客户端请求增加图片点击次数埋点，可以直接对接到重构后的后端
		r.GET("/api/image/point", api.AddImagePointTime)

		旧的福uu客户端通过学号设备请求开屏页，同样可以直接对接到重构后的后端，
		前端发送的结构体定义在飞书文档API.MobileGetImage
		飞书文档:https://west2-online.feishu.cn/wiki/YMtTwhwAOimxkIkeZfAcfAzgnle
		r.GET("/api/screen", api.MobileGetImage)
	*/
	r.GET("/api/image/point", custom.AddImagePointTime)
	r.GET("/api/screen", custom.MobileGetImage)

	// url服务的兼容
	/*
		旧的fuu客户端采取的是
		r.GET("/onekey/FZUHelper.html", api.FZUHelperHTML) 对应 福uu隐私政策
		r.GET("/onekey/UserAgreement.html", api.UserAgreementHTML) 对应 福uu用户服务协议

		隐私政策和用户协议对应url前缀
		const val USER_AGREEMENT = "https://iosfzuhelper.west2online.com/onekey/UserAgreement.html"
		const val PRIVACY_POLICY = "https://iosfzuhelper.west2online.com/onekey/FZUHelper.html"
		飞书文档：https://west2-online.feishu.cn/wiki/AGaHw9B2EiEV04knIHEczlTxn5f

		r.GET("/onekey/FZUHelper.css", api.FZUHelperCSS) FZUHelper.html需要这个来正常呈现结果

		r.GET("/version.json", api.GetReleaseVersion) 对应 发行版本信息获取
		r.GET("/versionbeta.json", api.GetBetaVersion) 对应 beta版本信息获取
		r.GET("/settings.php", api.GetCloudSetting) 对应 获取设置

		20241128兼容-2024肖垲
		改为了向本项目内的微服务请求
	*/
	r.GET("/onekey/FZUHelper.html", api.GetHtml)
	r.GET("/onekey/UserAgreement.html", api.GetUserAgreement)
	r.GET("/onekey/FZUHelper.css", api.GetCSS)
	r.GET("/settings.php", api.GetSetting)
	r.GET("/version.json", custom.GetReleaseVersionModify)
	r.GET("/versionbeta.json", custom.GetBetaVersionModify)

	r.GET("/api/v1/url/onekey/FZUHelper.html", api.GetHtml)
	r.GET("/api/v1/url/onekey/UserAgreement.html", api.GetUserAgreement)
	r.GET("/api/v1/url/onekey/FZUHelper.css", api.GetCSS)
	r.GET("/api/v1/url/dump", api.GetDump)
	r.GET("/api/v1/url/getcloud", api.GetCloud)
	r.GET("/api/v1/url/settings.php", api.GetSetting)
	r.GET("/api/v1/url/beta.apk", api.DownloadReleaseApk)
	r.GET("/api/v1/url/release.apk", api.DownloadReleaseApk)
	r.POST("/api/v1/url/test", api.GetTest)
	r.POST("/api/v1/url/setcloud", api.SetCloud)
}
