# Filebeat 输入配置
filebeat.inputs:
  - type: filestream
    id: "fzuhelper-id"  # 添加唯一的 ID
    enabled: true
    paths:
      - /usr/share/filebeat/logs/**/*.log
    json.keys_under_root: true
    json.add_error_key: true
    scan_frequency: 5s  # 调整扫描频率，默认为 10s

# Filebeat 输出配置
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs"
  retry:
    max_retries: 5  # 最大重试次数
    backoff: 5s     # 重试间隔

# Filebeat 注册表文件路径
filebeat.registry.path: /usr/share/filebeat/data/registry

# 模板配置
setup.template:
  name: "logs-template"  # 模板名称
  pattern: "logs-*"      # 模板匹配模式
  enabled: true          # 启用模板管理
  overwrite: false       # 不覆盖已存在的模板
  settings:
    index:
      number_of_shards: 1   # 分片数
      number_of_replicas: 1 # 副本数
