system:
  domain: "api"
  host: "0.0.0.0"
  port: "20001"


etcd:
  etcdHost: "etcd"
  etcdPort: "2379"


redis:
  redisHost: "fzu-helper-redis"
  redisPort: "6379"
  redisPassword: "fzu-helper"
  redisDbName: 0
