/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kitex v0.15.4. DO NOT EDIT.

package user

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/west2-online/fzuhelper-server/kitex_gen/model"
)

var (
	_ = model.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type UserServiceGetLoginDataArgs struct {
	Req *GetLoginDataRequest `thrift:"req,1" frugal:"1,default,GetLoginDataRequest" json:"req"`
}

func NewUserServiceGetLoginDataArgs() *UserServiceGetLoginDataArgs {
	return &UserServiceGetLoginDataArgs{}
}

func (p *UserServiceGetLoginDataArgs) InitDefault() {
}

var UserServiceGetLoginDataArgs_Req_DEFAULT *GetLoginDataRequest

func (p *UserServiceGetLoginDataArgs) GetReq() (v *GetLoginDataRequest) {
	if !p.IsSetReq() {
		return UserServiceGetLoginDataArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetLoginDataArgs) SetReq(val *GetLoginDataRequest) {
	p.Req = val
}

func (p *UserServiceGetLoginDataArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetLoginDataArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetLoginDataArgs(%+v)", *p)
}

func (p *UserServiceGetLoginDataArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserServiceGetLoginDataResult struct {
	Success *GetLoginDataResponse `thrift:"success,0,optional" frugal:"0,optional,GetLoginDataResponse" json:"success,omitempty"`
}

func NewUserServiceGetLoginDataResult() *UserServiceGetLoginDataResult {
	return &UserServiceGetLoginDataResult{}
}

func (p *UserServiceGetLoginDataResult) InitDefault() {
}

var UserServiceGetLoginDataResult_Success_DEFAULT *GetLoginDataResponse

func (p *UserServiceGetLoginDataResult) GetSuccess() (v *GetLoginDataResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetLoginDataResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetLoginDataResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLoginDataResponse)
}

func (p *UserServiceGetLoginDataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetLoginDataResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetLoginDataResult(%+v)", *p)
}

func (p *UserServiceGetLoginDataResult) GetResult() interface{} {
	return p.Success
}

type UserServiceGetUserInfoArgs struct {
	Request *GetUserInfoRequest `thrift:"request,1" frugal:"1,default,GetUserInfoRequest" json:"request"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Request_DEFAULT *GetUserInfoRequest

func (p *UserServiceGetUserInfoArgs) GetRequest() (v *GetUserInfoRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetUserInfoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetUserInfoArgs) SetRequest(val *GetUserInfoRequest) {
	p.Request = val
}

func (p *UserServiceGetUserInfoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

func (p *UserServiceGetUserInfoArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResponse

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResponse)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

func (p *UserServiceGetUserInfoResult) GetResult() interface{} {
	return p.Success
}

type UserServiceGetGetLoginDataForYJSYArgs struct {
	Request *GetLoginDataForYJSYRequest `thrift:"request,1" frugal:"1,default,GetLoginDataForYJSYRequest" json:"request"`
}

func NewUserServiceGetGetLoginDataForYJSYArgs() *UserServiceGetGetLoginDataForYJSYArgs {
	return &UserServiceGetGetLoginDataForYJSYArgs{}
}

func (p *UserServiceGetGetLoginDataForYJSYArgs) InitDefault() {
}

var UserServiceGetGetLoginDataForYJSYArgs_Request_DEFAULT *GetLoginDataForYJSYRequest

func (p *UserServiceGetGetLoginDataForYJSYArgs) GetRequest() (v *GetLoginDataForYJSYRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetGetLoginDataForYJSYArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetGetLoginDataForYJSYArgs) SetRequest(val *GetLoginDataForYJSYRequest) {
	p.Request = val
}

func (p *UserServiceGetGetLoginDataForYJSYArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetGetLoginDataForYJSYArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetGetLoginDataForYJSYArgs(%+v)", *p)
}

func (p *UserServiceGetGetLoginDataForYJSYArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceGetGetLoginDataForYJSYResult struct {
	Success *GetLoginDataForYJSYResponse `thrift:"success,0,optional" frugal:"0,optional,GetLoginDataForYJSYResponse" json:"success,omitempty"`
}

func NewUserServiceGetGetLoginDataForYJSYResult() *UserServiceGetGetLoginDataForYJSYResult {
	return &UserServiceGetGetLoginDataForYJSYResult{}
}

func (p *UserServiceGetGetLoginDataForYJSYResult) InitDefault() {
}

var UserServiceGetGetLoginDataForYJSYResult_Success_DEFAULT *GetLoginDataForYJSYResponse

func (p *UserServiceGetGetLoginDataForYJSYResult) GetSuccess() (v *GetLoginDataForYJSYResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetGetLoginDataForYJSYResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetGetLoginDataForYJSYResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLoginDataForYJSYResponse)
}

func (p *UserServiceGetGetLoginDataForYJSYResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetGetLoginDataForYJSYResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetGetLoginDataForYJSYResult(%+v)", *p)
}

func (p *UserServiceGetGetLoginDataForYJSYResult) GetResult() interface{} {
	return p.Success
}

type UserServiceGetInvitationCodeArgs struct {
	Request *GetInvitationCodeRequest `thrift:"request,1" frugal:"1,default,GetInvitationCodeRequest" json:"request"`
}

func NewUserServiceGetInvitationCodeArgs() *UserServiceGetInvitationCodeArgs {
	return &UserServiceGetInvitationCodeArgs{}
}

func (p *UserServiceGetInvitationCodeArgs) InitDefault() {
}

var UserServiceGetInvitationCodeArgs_Request_DEFAULT *GetInvitationCodeRequest

func (p *UserServiceGetInvitationCodeArgs) GetRequest() (v *GetInvitationCodeRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetInvitationCodeArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetInvitationCodeArgs) SetRequest(val *GetInvitationCodeRequest) {
	p.Request = val
}

func (p *UserServiceGetInvitationCodeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetInvitationCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetInvitationCodeArgs(%+v)", *p)
}

func (p *UserServiceGetInvitationCodeArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceGetInvitationCodeResult struct {
	Success *GetInvitationCodeResponse `thrift:"success,0,optional" frugal:"0,optional,GetInvitationCodeResponse" json:"success,omitempty"`
}

func NewUserServiceGetInvitationCodeResult() *UserServiceGetInvitationCodeResult {
	return &UserServiceGetInvitationCodeResult{}
}

func (p *UserServiceGetInvitationCodeResult) InitDefault() {
}

var UserServiceGetInvitationCodeResult_Success_DEFAULT *GetInvitationCodeResponse

func (p *UserServiceGetInvitationCodeResult) GetSuccess() (v *GetInvitationCodeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetInvitationCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetInvitationCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetInvitationCodeResponse)
}

func (p *UserServiceGetInvitationCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetInvitationCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetInvitationCodeResult(%+v)", *p)
}

func (p *UserServiceGetInvitationCodeResult) GetResult() interface{} {
	return p.Success
}

type UserServiceBindInvitationArgs struct {
	Request *BindInvitationRequest `thrift:"request,1" frugal:"1,default,BindInvitationRequest" json:"request"`
}

func NewUserServiceBindInvitationArgs() *UserServiceBindInvitationArgs {
	return &UserServiceBindInvitationArgs{}
}

func (p *UserServiceBindInvitationArgs) InitDefault() {
}

var UserServiceBindInvitationArgs_Request_DEFAULT *BindInvitationRequest

func (p *UserServiceBindInvitationArgs) GetRequest() (v *BindInvitationRequest) {
	if !p.IsSetRequest() {
		return UserServiceBindInvitationArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceBindInvitationArgs) SetRequest(val *BindInvitationRequest) {
	p.Request = val
}

func (p *UserServiceBindInvitationArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceBindInvitationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBindInvitationArgs(%+v)", *p)
}

func (p *UserServiceBindInvitationArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceBindInvitationResult struct {
	Success *BindInvitationResponse `thrift:"success,0,optional" frugal:"0,optional,BindInvitationResponse" json:"success,omitempty"`
}

func NewUserServiceBindInvitationResult() *UserServiceBindInvitationResult {
	return &UserServiceBindInvitationResult{}
}

func (p *UserServiceBindInvitationResult) InitDefault() {
}

var UserServiceBindInvitationResult_Success_DEFAULT *BindInvitationResponse

func (p *UserServiceBindInvitationResult) GetSuccess() (v *BindInvitationResponse) {
	if !p.IsSetSuccess() {
		return UserServiceBindInvitationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceBindInvitationResult) SetSuccess(x interface{}) {
	p.Success = x.(*BindInvitationResponse)
}

func (p *UserServiceBindInvitationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceBindInvitationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBindInvitationResult(%+v)", *p)
}

func (p *UserServiceBindInvitationResult) GetResult() interface{} {
	return p.Success
}

type UserServiceGetFriendListArgs struct {
	Request *GetFriendListRequest `thrift:"request,1" frugal:"1,default,GetFriendListRequest" json:"request"`
}

func NewUserServiceGetFriendListArgs() *UserServiceGetFriendListArgs {
	return &UserServiceGetFriendListArgs{}
}

func (p *UserServiceGetFriendListArgs) InitDefault() {
}

var UserServiceGetFriendListArgs_Request_DEFAULT *GetFriendListRequest

func (p *UserServiceGetFriendListArgs) GetRequest() (v *GetFriendListRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetFriendListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetFriendListArgs) SetRequest(val *GetFriendListRequest) {
	p.Request = val
}

func (p *UserServiceGetFriendListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendListArgs(%+v)", *p)
}

func (p *UserServiceGetFriendListArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceGetFriendListResult struct {
	Success *GetFriendListResponse `thrift:"success,0,optional" frugal:"0,optional,GetFriendListResponse" json:"success,omitempty"`
}

func NewUserServiceGetFriendListResult() *UserServiceGetFriendListResult {
	return &UserServiceGetFriendListResult{}
}

func (p *UserServiceGetFriendListResult) InitDefault() {
}

var UserServiceGetFriendListResult_Success_DEFAULT *GetFriendListResponse

func (p *UserServiceGetFriendListResult) GetSuccess() (v *GetFriendListResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendListResponse)
}

func (p *UserServiceGetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendListResult(%+v)", *p)
}

func (p *UserServiceGetFriendListResult) GetResult() interface{} {
	return p.Success
}

type UserServiceDeleteFriendArgs struct {
	Request *DeleteFriendRequest `thrift:"request,1" frugal:"1,default,DeleteFriendRequest" json:"request"`
}

func NewUserServiceDeleteFriendArgs() *UserServiceDeleteFriendArgs {
	return &UserServiceDeleteFriendArgs{}
}

func (p *UserServiceDeleteFriendArgs) InitDefault() {
}

var UserServiceDeleteFriendArgs_Request_DEFAULT *DeleteFriendRequest

func (p *UserServiceDeleteFriendArgs) GetRequest() (v *DeleteFriendRequest) {
	if !p.IsSetRequest() {
		return UserServiceDeleteFriendArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceDeleteFriendArgs) SetRequest(val *DeleteFriendRequest) {
	p.Request = val
}

func (p *UserServiceDeleteFriendArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceDeleteFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendArgs(%+v)", *p)
}

func (p *UserServiceDeleteFriendArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceDeleteFriendResult struct {
	Success *DeleteFriendResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteFriendResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteFriendResult() *UserServiceDeleteFriendResult {
	return &UserServiceDeleteFriendResult{}
}

func (p *UserServiceDeleteFriendResult) InitDefault() {
}

var UserServiceDeleteFriendResult_Success_DEFAULT *DeleteFriendResponse

func (p *UserServiceDeleteFriendResult) GetSuccess() (v *DeleteFriendResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteFriendResponse)
}

func (p *UserServiceDeleteFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendResult(%+v)", *p)
}

func (p *UserServiceDeleteFriendResult) GetResult() interface{} {
	return p.Success
}

type UserServiceVerifyFriendArgs struct {
	Request *VerifyFriendRequest `thrift:"request,1" frugal:"1,default,VerifyFriendRequest" json:"request"`
}

func NewUserServiceVerifyFriendArgs() *UserServiceVerifyFriendArgs {
	return &UserServiceVerifyFriendArgs{}
}

func (p *UserServiceVerifyFriendArgs) InitDefault() {
}

var UserServiceVerifyFriendArgs_Request_DEFAULT *VerifyFriendRequest

func (p *UserServiceVerifyFriendArgs) GetRequest() (v *VerifyFriendRequest) {
	if !p.IsSetRequest() {
		return UserServiceVerifyFriendArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceVerifyFriendArgs) SetRequest(val *VerifyFriendRequest) {
	p.Request = val
}

func (p *UserServiceVerifyFriendArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceVerifyFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyFriendArgs(%+v)", *p)
}

func (p *UserServiceVerifyFriendArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceVerifyFriendResult struct {
	Success *VerifyFriendResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyFriendResponse" json:"success,omitempty"`
}

func NewUserServiceVerifyFriendResult() *UserServiceVerifyFriendResult {
	return &UserServiceVerifyFriendResult{}
}

func (p *UserServiceVerifyFriendResult) InitDefault() {
}

var UserServiceVerifyFriendResult_Success_DEFAULT *VerifyFriendResponse

func (p *UserServiceVerifyFriendResult) GetSuccess() (v *VerifyFriendResponse) {
	if !p.IsSetSuccess() {
		return UserServiceVerifyFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceVerifyFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyFriendResponse)
}

func (p *UserServiceVerifyFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceVerifyFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyFriendResult(%+v)", *p)
}

func (p *UserServiceVerifyFriendResult) GetResult() interface{} {
	return p.Success
}

type UserServiceCancelInviteArgs struct {
	Request *CancelInviteRequest `thrift:"request,1" frugal:"1,default,CancelInviteRequest" json:"request"`
}

func NewUserServiceCancelInviteArgs() *UserServiceCancelInviteArgs {
	return &UserServiceCancelInviteArgs{}
}

func (p *UserServiceCancelInviteArgs) InitDefault() {
}

var UserServiceCancelInviteArgs_Request_DEFAULT *CancelInviteRequest

func (p *UserServiceCancelInviteArgs) GetRequest() (v *CancelInviteRequest) {
	if !p.IsSetRequest() {
		return UserServiceCancelInviteArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceCancelInviteArgs) SetRequest(val *CancelInviteRequest) {
	p.Request = val
}

func (p *UserServiceCancelInviteArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceCancelInviteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCancelInviteArgs(%+v)", *p)
}

func (p *UserServiceCancelInviteArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceCancelInviteResult struct {
	Success *CancelInviteResponse `thrift:"success,0,optional" frugal:"0,optional,CancelInviteResponse" json:"success,omitempty"`
}

func NewUserServiceCancelInviteResult() *UserServiceCancelInviteResult {
	return &UserServiceCancelInviteResult{}
}

func (p *UserServiceCancelInviteResult) InitDefault() {
}

var UserServiceCancelInviteResult_Success_DEFAULT *CancelInviteResponse

func (p *UserServiceCancelInviteResult) GetSuccess() (v *CancelInviteResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCancelInviteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCancelInviteResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelInviteResponse)
}

func (p *UserServiceCancelInviteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCancelInviteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCancelInviteResult(%+v)", *p)
}

func (p *UserServiceCancelInviteResult) GetResult() interface{} {
	return p.Success
}

type UserServiceGetFriendMaxNumArgs struct {
	Request *GetFriendMaxNumRequest `thrift:"request,1" frugal:"1,default,GetFriendMaxNumRequest" json:"request"`
}

func NewUserServiceGetFriendMaxNumArgs() *UserServiceGetFriendMaxNumArgs {
	return &UserServiceGetFriendMaxNumArgs{}
}

func (p *UserServiceGetFriendMaxNumArgs) InitDefault() {
}

var UserServiceGetFriendMaxNumArgs_Request_DEFAULT *GetFriendMaxNumRequest

func (p *UserServiceGetFriendMaxNumArgs) GetRequest() (v *GetFriendMaxNumRequest) {
	if !p.IsSetRequest() {
		return UserServiceGetFriendMaxNumArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceGetFriendMaxNumArgs) SetRequest(val *GetFriendMaxNumRequest) {
	p.Request = val
}

func (p *UserServiceGetFriendMaxNumArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceGetFriendMaxNumArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendMaxNumArgs(%+v)", *p)
}

func (p *UserServiceGetFriendMaxNumArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceGetFriendMaxNumResult struct {
	Success *GetFriendMaxNumResponse `thrift:"success,0,optional" frugal:"0,optional,GetFriendMaxNumResponse" json:"success,omitempty"`
}

func NewUserServiceGetFriendMaxNumResult() *UserServiceGetFriendMaxNumResult {
	return &UserServiceGetFriendMaxNumResult{}
}

func (p *UserServiceGetFriendMaxNumResult) InitDefault() {
}

var UserServiceGetFriendMaxNumResult_Success_DEFAULT *GetFriendMaxNumResponse

func (p *UserServiceGetFriendMaxNumResult) GetSuccess() (v *GetFriendMaxNumResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetFriendMaxNumResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetFriendMaxNumResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendMaxNumResponse)
}

func (p *UserServiceGetFriendMaxNumResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetFriendMaxNumResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetFriendMaxNumResult(%+v)", *p)
}

func (p *UserServiceGetFriendMaxNumResult) GetResult() interface{} {
	return p.Success
}

type UserServiceReorderFriendListArgs struct {
	Request *ReorderFriendListRequest `thrift:"request,1" frugal:"1,default,ReorderFriendListRequest" json:"request"`
}

func NewUserServiceReorderFriendListArgs() *UserServiceReorderFriendListArgs {
	return &UserServiceReorderFriendListArgs{}
}

func (p *UserServiceReorderFriendListArgs) InitDefault() {
}

var UserServiceReorderFriendListArgs_Request_DEFAULT *ReorderFriendListRequest

func (p *UserServiceReorderFriendListArgs) GetRequest() (v *ReorderFriendListRequest) {
	if !p.IsSetRequest() {
		return UserServiceReorderFriendListArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserServiceReorderFriendListArgs) SetRequest(val *ReorderFriendListRequest) {
	p.Request = val
}

func (p *UserServiceReorderFriendListArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceReorderFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceReorderFriendListArgs(%+v)", *p)
}

func (p *UserServiceReorderFriendListArgs) GetFirstArgument() interface{} {
	return p.Request
}

type UserServiceReorderFriendListResult struct {
	Success *ReorderFriendListResponse `thrift:"success,0,optional" frugal:"0,optional,ReorderFriendListResponse" json:"success,omitempty"`
}

func NewUserServiceReorderFriendListResult() *UserServiceReorderFriendListResult {
	return &UserServiceReorderFriendListResult{}
}

func (p *UserServiceReorderFriendListResult) InitDefault() {
}

var UserServiceReorderFriendListResult_Success_DEFAULT *ReorderFriendListResponse

func (p *UserServiceReorderFriendListResult) GetSuccess() (v *ReorderFriendListResponse) {
	if !p.IsSetSuccess() {
		return UserServiceReorderFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceReorderFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReorderFriendListResponse)
}

func (p *UserServiceReorderFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceReorderFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceReorderFriendListResult(%+v)", *p)
}

func (p *UserServiceReorderFriendListResult) GetResult() interface{} {
	return p.Success
}
