/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"

	"github.com/west2-online/fzuhelper-server/kitex_gen/model"
)

type GetLoginDataRequest struct {
	Id       string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewGetLoginDataRequest() *GetLoginDataRequest {
	return &GetLoginDataRequest{}
}

func (p *GetLoginDataRequest) InitDefault() {
}

func (p *GetLoginDataRequest) GetId() (v string) {
	return p.Id
}

func (p *GetLoginDataRequest) GetPassword() (v string) {
	return p.Password
}
func (p *GetLoginDataRequest) SetId(val string) {
	p.Id = val
}
func (p *GetLoginDataRequest) SetPassword(val string) {
	p.Password = val
}

func (p *GetLoginDataRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLoginDataRequest(%+v)", *p)
}

type GetLoginDataResponse struct {
	Base    *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Id      string          `thrift:"id,2,required" frugal:"2,required,string" json:"id"`
	Cookies string          `thrift:"cookies,3,required" frugal:"3,required,string" json:"cookies"`
}

func NewGetLoginDataResponse() *GetLoginDataResponse {
	return &GetLoginDataResponse{}
}

func (p *GetLoginDataResponse) InitDefault() {
}

var GetLoginDataResponse_Base_DEFAULT *model.BaseResp

func (p *GetLoginDataResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetLoginDataResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetLoginDataResponse) GetId() (v string) {
	return p.Id
}

func (p *GetLoginDataResponse) GetCookies() (v string) {
	return p.Cookies
}
func (p *GetLoginDataResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetLoginDataResponse) SetId(val string) {
	p.Id = val
}
func (p *GetLoginDataResponse) SetCookies(val string) {
	p.Cookies = val
}

func (p *GetLoginDataResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetLoginDataResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLoginDataResponse(%+v)", *p)
}

type GetUserInfoRequest struct {
}

func NewGetUserInfoRequest() *GetUserInfoRequest {
	return &GetUserInfoRequest{}
}

func (p *GetUserInfoRequest) InitDefault() {
}

func (p *GetUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoRequest(%+v)", *p)
}

type GetUserInfoResponse struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Data *model.UserInfo `thrift:"data,2,optional" frugal:"2,optional,model.UserInfo" json:"data,omitempty"`
}

func NewGetUserInfoResponse() *GetUserInfoResponse {
	return &GetUserInfoResponse{}
}

func (p *GetUserInfoResponse) InitDefault() {
}

var GetUserInfoResponse_Base_DEFAULT *model.BaseResp

func (p *GetUserInfoResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetUserInfoResponse_Base_DEFAULT
	}
	return p.Base
}

var GetUserInfoResponse_Data_DEFAULT *model.UserInfo

func (p *GetUserInfoResponse) GetData() (v *model.UserInfo) {
	if !p.IsSetData() {
		return GetUserInfoResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *GetUserInfoResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetUserInfoResponse) SetData(val *model.UserInfo) {
	p.Data = val
}

func (p *GetUserInfoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResponse(%+v)", *p)
}

type GetLoginDataForYJSYRequest struct {
	Id       string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewGetLoginDataForYJSYRequest() *GetLoginDataForYJSYRequest {
	return &GetLoginDataForYJSYRequest{}
}

func (p *GetLoginDataForYJSYRequest) InitDefault() {
}

func (p *GetLoginDataForYJSYRequest) GetId() (v string) {
	return p.Id
}

func (p *GetLoginDataForYJSYRequest) GetPassword() (v string) {
	return p.Password
}
func (p *GetLoginDataForYJSYRequest) SetId(val string) {
	p.Id = val
}
func (p *GetLoginDataForYJSYRequest) SetPassword(val string) {
	p.Password = val
}

func (p *GetLoginDataForYJSYRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLoginDataForYJSYRequest(%+v)", *p)
}

type GetLoginDataForYJSYResponse struct {
	Base    *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Id      string          `thrift:"id,2,required" frugal:"2,required,string" json:"id"`
	Cookies string          `thrift:"cookies,3,required" frugal:"3,required,string" json:"cookies"`
}

func NewGetLoginDataForYJSYResponse() *GetLoginDataForYJSYResponse {
	return &GetLoginDataForYJSYResponse{}
}

func (p *GetLoginDataForYJSYResponse) InitDefault() {
}

var GetLoginDataForYJSYResponse_Base_DEFAULT *model.BaseResp

func (p *GetLoginDataForYJSYResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetLoginDataForYJSYResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetLoginDataForYJSYResponse) GetId() (v string) {
	return p.Id
}

func (p *GetLoginDataForYJSYResponse) GetCookies() (v string) {
	return p.Cookies
}
func (p *GetLoginDataForYJSYResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetLoginDataForYJSYResponse) SetId(val string) {
	p.Id = val
}
func (p *GetLoginDataForYJSYResponse) SetCookies(val string) {
	p.Cookies = val
}

func (p *GetLoginDataForYJSYResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetLoginDataForYJSYResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLoginDataForYJSYResponse(%+v)", *p)
}

type GetInvitationCodeRequest struct {
	IsRefresh *bool `thrift:"isRefresh,1,optional" frugal:"1,optional,bool" json:"isRefresh,omitempty"`
}

func NewGetInvitationCodeRequest() *GetInvitationCodeRequest {
	return &GetInvitationCodeRequest{}
}

func (p *GetInvitationCodeRequest) InitDefault() {
}

var GetInvitationCodeRequest_IsRefresh_DEFAULT bool

func (p *GetInvitationCodeRequest) GetIsRefresh() (v bool) {
	if !p.IsSetIsRefresh() {
		return GetInvitationCodeRequest_IsRefresh_DEFAULT
	}
	return *p.IsRefresh
}
func (p *GetInvitationCodeRequest) SetIsRefresh(val *bool) {
	p.IsRefresh = val
}

func (p *GetInvitationCodeRequest) IsSetIsRefresh() bool {
	return p.IsRefresh != nil
}

func (p *GetInvitationCodeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInvitationCodeRequest(%+v)", *p)
}

type GetInvitationCodeResponse struct {
	Base           *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	InvitationCode string          `thrift:"invitation_code,2,required" frugal:"2,required,string" json:"invitation_code"`
	ExpireAt       int64           `thrift:"expire_at,3,required" frugal:"3,required,i64" json:"expire_at"`
}

func NewGetInvitationCodeResponse() *GetInvitationCodeResponse {
	return &GetInvitationCodeResponse{}
}

func (p *GetInvitationCodeResponse) InitDefault() {
}

var GetInvitationCodeResponse_Base_DEFAULT *model.BaseResp

func (p *GetInvitationCodeResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetInvitationCodeResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *GetInvitationCodeResponse) GetInvitationCode() (v string) {
	return p.InvitationCode
}

func (p *GetInvitationCodeResponse) GetExpireAt() (v int64) {
	return p.ExpireAt
}
func (p *GetInvitationCodeResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetInvitationCodeResponse) SetInvitationCode(val string) {
	p.InvitationCode = val
}
func (p *GetInvitationCodeResponse) SetExpireAt(val int64) {
	p.ExpireAt = val
}

func (p *GetInvitationCodeResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetInvitationCodeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInvitationCodeResponse(%+v)", *p)
}

type BindInvitationRequest struct {
	InvitationCode string `thrift:"invitation_code,1,required" frugal:"1,required,string" json:"invitation_code"`
}

func NewBindInvitationRequest() *BindInvitationRequest {
	return &BindInvitationRequest{}
}

func (p *BindInvitationRequest) InitDefault() {
}

func (p *BindInvitationRequest) GetInvitationCode() (v string) {
	return p.InvitationCode
}
func (p *BindInvitationRequest) SetInvitationCode(val string) {
	p.InvitationCode = val
}

func (p *BindInvitationRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindInvitationRequest(%+v)", *p)
}

type BindInvitationResponse struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewBindInvitationResponse() *BindInvitationResponse {
	return &BindInvitationResponse{}
}

func (p *BindInvitationResponse) InitDefault() {
}

var BindInvitationResponse_Base_DEFAULT *model.BaseResp

func (p *BindInvitationResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return BindInvitationResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *BindInvitationResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *BindInvitationResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *BindInvitationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindInvitationResponse(%+v)", *p)
}

type GetFriendListRequest struct {
}

func NewGetFriendListRequest() *GetFriendListRequest {
	return &GetFriendListRequest{}
}

func (p *GetFriendListRequest) InitDefault() {
}

func (p *GetFriendListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListRequest(%+v)", *p)
}

type GetFriendListResponse struct {
	Base *model.BaseResp         `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Data []*model.UserFriendInfo `thrift:"data,2,optional" frugal:"2,optional,list<model.UserFriendInfo>" json:"data,omitempty"`
}

func NewGetFriendListResponse() *GetFriendListResponse {
	return &GetFriendListResponse{}
}

func (p *GetFriendListResponse) InitDefault() {
}

var GetFriendListResponse_Base_DEFAULT *model.BaseResp

func (p *GetFriendListResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetFriendListResponse_Base_DEFAULT
	}
	return p.Base
}

var GetFriendListResponse_Data_DEFAULT []*model.UserFriendInfo

func (p *GetFriendListResponse) GetData() (v []*model.UserFriendInfo) {
	if !p.IsSetData() {
		return GetFriendListResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *GetFriendListResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetFriendListResponse) SetData(val []*model.UserFriendInfo) {
	p.Data = val
}

func (p *GetFriendListResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetFriendListResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetFriendListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListResponse(%+v)", *p)
}

type DeleteFriendRequest struct {
	Id string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
}

func NewDeleteFriendRequest() *DeleteFriendRequest {
	return &DeleteFriendRequest{}
}

func (p *DeleteFriendRequest) InitDefault() {
}

func (p *DeleteFriendRequest) GetId() (v string) {
	return p.Id
}
func (p *DeleteFriendRequest) SetId(val string) {
	p.Id = val
}

func (p *DeleteFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendRequest(%+v)", *p)
}

type DeleteFriendResponse struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewDeleteFriendResponse() *DeleteFriendResponse {
	return &DeleteFriendResponse{}
}

func (p *DeleteFriendResponse) InitDefault() {
}

var DeleteFriendResponse_Base_DEFAULT *model.BaseResp

func (p *DeleteFriendResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return DeleteFriendResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteFriendResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *DeleteFriendResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteFriendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendResponse(%+v)", *p)
}

type VerifyFriendRequest struct {
	Id       string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	FriendId string `thrift:"friend_id,2,required" frugal:"2,required,string" json:"friend_id"`
}

func NewVerifyFriendRequest() *VerifyFriendRequest {
	return &VerifyFriendRequest{}
}

func (p *VerifyFriendRequest) InitDefault() {
}

func (p *VerifyFriendRequest) GetId() (v string) {
	return p.Id
}

func (p *VerifyFriendRequest) GetFriendId() (v string) {
	return p.FriendId
}
func (p *VerifyFriendRequest) SetId(val string) {
	p.Id = val
}
func (p *VerifyFriendRequest) SetFriendId(val string) {
	p.FriendId = val
}

func (p *VerifyFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyFriendRequest(%+v)", *p)
}

type VerifyFriendResponse struct {
	Base        *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	FriendExist bool            `thrift:"friend_exist,2,required" frugal:"2,required,bool" json:"friend_exist"`
}

func NewVerifyFriendResponse() *VerifyFriendResponse {
	return &VerifyFriendResponse{}
}

func (p *VerifyFriendResponse) InitDefault() {
}

var VerifyFriendResponse_Base_DEFAULT *model.BaseResp

func (p *VerifyFriendResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return VerifyFriendResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *VerifyFriendResponse) GetFriendExist() (v bool) {
	return p.FriendExist
}
func (p *VerifyFriendResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *VerifyFriendResponse) SetFriendExist(val bool) {
	p.FriendExist = val
}

func (p *VerifyFriendResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *VerifyFriendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyFriendResponse(%+v)", *p)
}

type CancelInviteRequest struct {
}

func NewCancelInviteRequest() *CancelInviteRequest {
	return &CancelInviteRequest{}
}

func (p *CancelInviteRequest) InitDefault() {
}

func (p *CancelInviteRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelInviteRequest(%+v)", *p)
}

type CancelInviteResponse struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewCancelInviteResponse() *CancelInviteResponse {
	return &CancelInviteResponse{}
}

func (p *CancelInviteResponse) InitDefault() {
}

var CancelInviteResponse_Base_DEFAULT *model.BaseResp

func (p *CancelInviteResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return CancelInviteResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *CancelInviteResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *CancelInviteResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *CancelInviteResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelInviteResponse(%+v)", *p)
}

type GetFriendMaxNumRequest struct {
}

func NewGetFriendMaxNumRequest() *GetFriendMaxNumRequest {
	return &GetFriendMaxNumRequest{}
}

func (p *GetFriendMaxNumRequest) InitDefault() {
}

func (p *GetFriendMaxNumRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendMaxNumRequest(%+v)", *p)
}

type GetFriendMaxNumResponse struct {
	Base *model.BaseResp         `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
	Data *model.FriendMaxNumInfo `thrift:"data,2,required" frugal:"2,required,model.FriendMaxNumInfo" json:"data"`
}

func NewGetFriendMaxNumResponse() *GetFriendMaxNumResponse {
	return &GetFriendMaxNumResponse{}
}

func (p *GetFriendMaxNumResponse) InitDefault() {
}

var GetFriendMaxNumResponse_Base_DEFAULT *model.BaseResp

func (p *GetFriendMaxNumResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return GetFriendMaxNumResponse_Base_DEFAULT
	}
	return p.Base
}

var GetFriendMaxNumResponse_Data_DEFAULT *model.FriendMaxNumInfo

func (p *GetFriendMaxNumResponse) GetData() (v *model.FriendMaxNumInfo) {
	if !p.IsSetData() {
		return GetFriendMaxNumResponse_Data_DEFAULT
	}
	return p.Data
}
func (p *GetFriendMaxNumResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}
func (p *GetFriendMaxNumResponse) SetData(val *model.FriendMaxNumInfo) {
	p.Data = val
}

func (p *GetFriendMaxNumResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetFriendMaxNumResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetFriendMaxNumResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendMaxNumResponse(%+v)", *p)
}

type ReorderFriendListRequest struct {
	FriendIds []string `thrift:"friend_ids,1,required" frugal:"1,required,list<string>" json:"friend_ids"`
}

func NewReorderFriendListRequest() *ReorderFriendListRequest {
	return &ReorderFriendListRequest{}
}

func (p *ReorderFriendListRequest) InitDefault() {
}

func (p *ReorderFriendListRequest) GetFriendIds() (v []string) {
	return p.FriendIds
}
func (p *ReorderFriendListRequest) SetFriendIds(val []string) {
	p.FriendIds = val
}

func (p *ReorderFriendListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReorderFriendListRequest(%+v)", *p)
}

type ReorderFriendListResponse struct {
	Base *model.BaseResp `thrift:"base,1,required" frugal:"1,required,model.BaseResp" json:"base"`
}

func NewReorderFriendListResponse() *ReorderFriendListResponse {
	return &ReorderFriendListResponse{}
}

func (p *ReorderFriendListResponse) InitDefault() {
}

var ReorderFriendListResponse_Base_DEFAULT *model.BaseResp

func (p *ReorderFriendListResponse) GetBase() (v *model.BaseResp) {
	if !p.IsSetBase() {
		return ReorderFriendListResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ReorderFriendListResponse) SetBase(val *model.BaseResp) {
	p.Base = val
}

func (p *ReorderFriendListResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ReorderFriendListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReorderFriendListResponse(%+v)", *p)
}

type UserService interface {
	GetLoginData(ctx context.Context, req *GetLoginDataRequest) (r *GetLoginDataResponse, err error)

	GetUserInfo(ctx context.Context, request *GetUserInfoRequest) (r *GetUserInfoResponse, err error)

	GetGetLoginDataForYJSY(ctx context.Context, request *GetLoginDataForYJSYRequest) (r *GetLoginDataForYJSYResponse, err error)

	GetInvitationCode(ctx context.Context, request *GetInvitationCodeRequest) (r *GetInvitationCodeResponse, err error)

	BindInvitation(ctx context.Context, request *BindInvitationRequest) (r *BindInvitationResponse, err error)

	GetFriendList(ctx context.Context, request *GetFriendListRequest) (r *GetFriendListResponse, err error)

	DeleteFriend(ctx context.Context, request *DeleteFriendRequest) (r *DeleteFriendResponse, err error)

	VerifyFriend(ctx context.Context, request *VerifyFriendRequest) (r *VerifyFriendResponse, err error)

	CancelInvite(ctx context.Context, request *CancelInviteRequest) (r *CancelInviteResponse, err error)

	GetFriendMaxNum(ctx context.Context, request *GetFriendMaxNumRequest) (r *GetFriendMaxNumResponse, err error)

	ReorderFriendList(ctx context.Context, request *ReorderFriendListRequest) (r *ReorderFriendListResponse, err error)
}
