/*
Copyright 2024 The west2-online Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kitex v0.15.4. DO NOT EDIT.

package academic

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/west2-online/fzuhelper-server/kitex_gen/model"
)

var (
	_ = model.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)

type AcademicServiceGetScoresArgs struct {
	Req *GetScoresRequest `thrift:"req,1" frugal:"1,default,GetScoresRequest" json:"req"`
}

func NewAcademicServiceGetScoresArgs() *AcademicServiceGetScoresArgs {
	return &AcademicServiceGetScoresArgs{}
}

func (p *AcademicServiceGetScoresArgs) InitDefault() {
}

var AcademicServiceGetScoresArgs_Req_DEFAULT *GetScoresRequest

func (p *AcademicServiceGetScoresArgs) GetReq() (v *GetScoresRequest) {
	if !p.IsSetReq() {
		return AcademicServiceGetScoresArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetScoresArgs) SetReq(val *GetScoresRequest) {
	p.Req = val
}

func (p *AcademicServiceGetScoresArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetScoresArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetScoresArgs(%+v)", *p)
}

func (p *AcademicServiceGetScoresArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetScoresResult struct {
	Success *GetScoresResponse `thrift:"success,0,optional" frugal:"0,optional,GetScoresResponse" json:"success,omitempty"`
}

func NewAcademicServiceGetScoresResult() *AcademicServiceGetScoresResult {
	return &AcademicServiceGetScoresResult{}
}

func (p *AcademicServiceGetScoresResult) InitDefault() {
}

var AcademicServiceGetScoresResult_Success_DEFAULT *GetScoresResponse

func (p *AcademicServiceGetScoresResult) GetSuccess() (v *GetScoresResponse) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetScoresResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetScoresResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetScoresResponse)
}

func (p *AcademicServiceGetScoresResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetScoresResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetScoresResult(%+v)", *p)
}

func (p *AcademicServiceGetScoresResult) GetResult() interface{} {
	return p.Success
}

type AcademicServiceGetGPAArgs struct {
	Req *GetGPARequest `thrift:"req,1" frugal:"1,default,GetGPARequest" json:"req"`
}

func NewAcademicServiceGetGPAArgs() *AcademicServiceGetGPAArgs {
	return &AcademicServiceGetGPAArgs{}
}

func (p *AcademicServiceGetGPAArgs) InitDefault() {
}

var AcademicServiceGetGPAArgs_Req_DEFAULT *GetGPARequest

func (p *AcademicServiceGetGPAArgs) GetReq() (v *GetGPARequest) {
	if !p.IsSetReq() {
		return AcademicServiceGetGPAArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetGPAArgs) SetReq(val *GetGPARequest) {
	p.Req = val
}

func (p *AcademicServiceGetGPAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetGPAArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetGPAArgs(%+v)", *p)
}

func (p *AcademicServiceGetGPAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetGPAResult struct {
	Success *GetGPAResponse `thrift:"success,0,optional" frugal:"0,optional,GetGPAResponse" json:"success,omitempty"`
}

func NewAcademicServiceGetGPAResult() *AcademicServiceGetGPAResult {
	return &AcademicServiceGetGPAResult{}
}

func (p *AcademicServiceGetGPAResult) InitDefault() {
}

var AcademicServiceGetGPAResult_Success_DEFAULT *GetGPAResponse

func (p *AcademicServiceGetGPAResult) GetSuccess() (v *GetGPAResponse) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetGPAResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetGPAResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetGPAResponse)
}

func (p *AcademicServiceGetGPAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetGPAResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetGPAResult(%+v)", *p)
}

func (p *AcademicServiceGetGPAResult) GetResult() interface{} {
	return p.Success
}

type AcademicServiceGetCreditArgs struct {
	Req *GetCreditRequest `thrift:"req,1" frugal:"1,default,GetCreditRequest" json:"req"`
}

func NewAcademicServiceGetCreditArgs() *AcademicServiceGetCreditArgs {
	return &AcademicServiceGetCreditArgs{}
}

func (p *AcademicServiceGetCreditArgs) InitDefault() {
}

var AcademicServiceGetCreditArgs_Req_DEFAULT *GetCreditRequest

func (p *AcademicServiceGetCreditArgs) GetReq() (v *GetCreditRequest) {
	if !p.IsSetReq() {
		return AcademicServiceGetCreditArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetCreditArgs) SetReq(val *GetCreditRequest) {
	p.Req = val
}

func (p *AcademicServiceGetCreditArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetCreditArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetCreditArgs(%+v)", *p)
}

func (p *AcademicServiceGetCreditArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetCreditResult struct {
	Success *GetCreditResponse `thrift:"success,0,optional" frugal:"0,optional,GetCreditResponse" json:"success,omitempty"`
}

func NewAcademicServiceGetCreditResult() *AcademicServiceGetCreditResult {
	return &AcademicServiceGetCreditResult{}
}

func (p *AcademicServiceGetCreditResult) InitDefault() {
}

var AcademicServiceGetCreditResult_Success_DEFAULT *GetCreditResponse

func (p *AcademicServiceGetCreditResult) GetSuccess() (v *GetCreditResponse) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetCreditResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetCreditResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCreditResponse)
}

func (p *AcademicServiceGetCreditResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetCreditResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetCreditResult(%+v)", *p)
}

func (p *AcademicServiceGetCreditResult) GetResult() interface{} {
	return p.Success
}

type AcademicServiceGetUnifiedExamArgs struct {
	Req *GetUnifiedExamRequest `thrift:"req,1" frugal:"1,default,GetUnifiedExamRequest" json:"req"`
}

func NewAcademicServiceGetUnifiedExamArgs() *AcademicServiceGetUnifiedExamArgs {
	return &AcademicServiceGetUnifiedExamArgs{}
}

func (p *AcademicServiceGetUnifiedExamArgs) InitDefault() {
}

var AcademicServiceGetUnifiedExamArgs_Req_DEFAULT *GetUnifiedExamRequest

func (p *AcademicServiceGetUnifiedExamArgs) GetReq() (v *GetUnifiedExamRequest) {
	if !p.IsSetReq() {
		return AcademicServiceGetUnifiedExamArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetUnifiedExamArgs) SetReq(val *GetUnifiedExamRequest) {
	p.Req = val
}

func (p *AcademicServiceGetUnifiedExamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetUnifiedExamArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetUnifiedExamArgs(%+v)", *p)
}

func (p *AcademicServiceGetUnifiedExamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetUnifiedExamResult struct {
	Success *GetUnifiedExamResponse `thrift:"success,0,optional" frugal:"0,optional,GetUnifiedExamResponse" json:"success,omitempty"`
}

func NewAcademicServiceGetUnifiedExamResult() *AcademicServiceGetUnifiedExamResult {
	return &AcademicServiceGetUnifiedExamResult{}
}

func (p *AcademicServiceGetUnifiedExamResult) InitDefault() {
}

var AcademicServiceGetUnifiedExamResult_Success_DEFAULT *GetUnifiedExamResponse

func (p *AcademicServiceGetUnifiedExamResult) GetSuccess() (v *GetUnifiedExamResponse) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetUnifiedExamResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetUnifiedExamResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUnifiedExamResponse)
}

func (p *AcademicServiceGetUnifiedExamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetUnifiedExamResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetUnifiedExamResult(%+v)", *p)
}

func (p *AcademicServiceGetUnifiedExamResult) GetResult() interface{} {
	return p.Success
}

type AcademicServiceGetPlanArgs struct {
	Req *GetPlanRequest `thrift:"req,1" frugal:"1,default,GetPlanRequest" json:"req"`
}

func NewAcademicServiceGetPlanArgs() *AcademicServiceGetPlanArgs {
	return &AcademicServiceGetPlanArgs{}
}

func (p *AcademicServiceGetPlanArgs) InitDefault() {
}

var AcademicServiceGetPlanArgs_Req_DEFAULT *GetPlanRequest

func (p *AcademicServiceGetPlanArgs) GetReq() (v *GetPlanRequest) {
	if !p.IsSetReq() {
		return AcademicServiceGetPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetPlanArgs) SetReq(val *GetPlanRequest) {
	p.Req = val
}

func (p *AcademicServiceGetPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetPlanArgs(%+v)", *p)
}

func (p *AcademicServiceGetPlanArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetPlanResult struct {
	Success *GetPlanResponse `thrift:"success,0,optional" frugal:"0,optional,GetPlanResponse" json:"success,omitempty"`
}

func NewAcademicServiceGetPlanResult() *AcademicServiceGetPlanResult {
	return &AcademicServiceGetPlanResult{}
}

func (p *AcademicServiceGetPlanResult) InitDefault() {
}

var AcademicServiceGetPlanResult_Success_DEFAULT *GetPlanResponse

func (p *AcademicServiceGetPlanResult) GetSuccess() (v *GetPlanResponse) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPlanResponse)
}

func (p *AcademicServiceGetPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetPlanResult(%+v)", *p)
}

func (p *AcademicServiceGetPlanResult) GetResult() interface{} {
	return p.Success
}

type AcademicServiceGetCreditV2Args struct {
	Req *GetCreditV2Request `thrift:"req,1" frugal:"1,default,GetCreditV2Request" json:"req"`
}

func NewAcademicServiceGetCreditV2Args() *AcademicServiceGetCreditV2Args {
	return &AcademicServiceGetCreditV2Args{}
}

func (p *AcademicServiceGetCreditV2Args) InitDefault() {
}

var AcademicServiceGetCreditV2Args_Req_DEFAULT *GetCreditV2Request

func (p *AcademicServiceGetCreditV2Args) GetReq() (v *GetCreditV2Request) {
	if !p.IsSetReq() {
		return AcademicServiceGetCreditV2Args_Req_DEFAULT
	}
	return p.Req
}
func (p *AcademicServiceGetCreditV2Args) SetReq(val *GetCreditV2Request) {
	p.Req = val
}

func (p *AcademicServiceGetCreditV2Args) IsSetReq() bool {
	return p.Req != nil
}

func (p *AcademicServiceGetCreditV2Args) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetCreditV2Args(%+v)", *p)
}

func (p *AcademicServiceGetCreditV2Args) GetFirstArgument() interface{} {
	return p.Req
}

type AcademicServiceGetCreditV2Result struct {
	Success *GetCreditV2Response `thrift:"success,0,optional" frugal:"0,optional,GetCreditV2Response" json:"success,omitempty"`
}

func NewAcademicServiceGetCreditV2Result() *AcademicServiceGetCreditV2Result {
	return &AcademicServiceGetCreditV2Result{}
}

func (p *AcademicServiceGetCreditV2Result) InitDefault() {
}

var AcademicServiceGetCreditV2Result_Success_DEFAULT *GetCreditV2Response

func (p *AcademicServiceGetCreditV2Result) GetSuccess() (v *GetCreditV2Response) {
	if !p.IsSetSuccess() {
		return AcademicServiceGetCreditV2Result_Success_DEFAULT
	}
	return p.Success
}
func (p *AcademicServiceGetCreditV2Result) SetSuccess(x interface{}) {
	p.Success = x.(*GetCreditV2Response)
}

func (p *AcademicServiceGetCreditV2Result) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AcademicServiceGetCreditV2Result) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AcademicServiceGetCreditV2Result(%+v)", *p)
}

func (p *AcademicServiceGetCreditV2Result) GetResult() interface{} {
	return p.Success
}
