// Code generated by Kitex v0.8.0. DO NOT EDIT.

package emptyroomservice

import (
	server "github.com/cloudwego/kitex/server"
	empty_room "github.com/west2-online/fzuhelper-server/kitex_gen/empty_room"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler empty_room.EmptyRoomService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
